const translations = {
    ko: {
        "index_button_introduce" : "서울로미디어캔버스 소개",
        "index_button_schedule" : "상영 시간표",
        "index_button_exhibit" : "전시 소개",
        "index_button_exhibit_sub" : "",
        "index_button_art_1" : "동행 모먼트서울",
        "index_button_art_1_sub" : "Moment Seoul",
        "index_button_art_2" : "매력 한강네이처",
        "index_button_art_2_sub" : "Hangang Nature",
        "index_button_directions" : "오시는 길",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        // "atelier_nodeul_name" : "아뜰리에 노들",
        // "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        // "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        // "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<아뜰리에 노들 2026 첫 번째 전시 : 시작의 근원> 전시 시간표",
        "schedule_explain_date" : "전시 기간: 2026.05.22.(금) ~ 2026.07.31.(금)",
        "schedule_explain_pos" : "상영 장소: 노들섬 남단 한강대교 교각 하부 미디어파사드",
        "schedule_explain_pos_detail" : "노들섬 아트라운지 미디어볼 상명 시간",
        "schedule_explain_time" : "상영 시간: 20:00 ~ 22:00 (매 시각 정시 상영)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        // "exhibit_intro_title" : "전시 소개",        
        // "exhibit_introduce_name" : "2026 아뜰리에 노들 첫 전시 : 시작의 근원\nAtelier Nodeul 2026 1st Exhibition : The Origin of All Beginnings",
        "exhibit_introduce" : "서울로미디어캔버스는 시민이 향유하고 공감할 수 있는\n미디어아트와 영상 콘텐츠 등 전자적 빛으로 이루어진\n예술작품을\n지속 전시하여 미디어아트의 영역을 확장하는 미디어아트\n전문 플랫폼입니다.",
        // "exhibit_introduce_sub" : "*특정 지역이나 환경을 대표하면서 사람들의 관심과 보호의식을 이끌어내기 위해 선정된 상징적인 생물종",
        // "exhibit_explain_name_1" : "시작의 근원",
        // "exhibit_explain_1" : "'시작의 근원 The Origin of All Beginnings'은 한강 노들섬에서 펼쳐지는 미디어아트 전시로, 도시의 빛과 물결이 교차하는 지점에서 기원과 생성의 순간을 탐구합니다.\n이돈아, 최성록 두 미디어아티스트의 다채롭고 역동적인 작품을 통해 노들섬의 예술적 매력과 한강의 새로운 가능성을 재조명합니다.",
        // "exhibit_explain_name_2" : "모먼트 서울",
        // "exhibit_explain_2" : "서울의 핵심 가치인 ‘약자와 동행하는 상생 도시’를 강조합니다.\n〈서울응원 메시지〉를 통해 새로운 시작을 앞둔 시민들에게 응원의 메시지를 전달하고, 〈해치와 서울나들이〉는 노들섬과 한강변을 배경으로, 노들섬에서 출발해 서울 상공으로 이어지는 여정을 그립니다.",
        // "exhibit_explain_name_3" : "한강 네이처",
        // "exhibit_explain_3" : "한강 네이처는 서울의 비전인 ‘매력’을 상징하며, 자연이 살아 숨 쉬는 한강 노들섬의 생태를 미디어아트로 풀어낸 자연도감입니다.\n맹꽁이를 주인공으로 한 옴니버스 애니메이션으로, 새로운 터전을 찾아가는 여정을 통해 노들섬의 생태와 계절의 변화, 그리고 서울과 한강의 다양한 모습을 전합니다.",
        
        "exhibit_2_intro_title" : "전시 소개",        
        "exhibit_2_introduce_name" : "두 번째 전시 07.01.-09.19.",
        "exhibit_2_introduce" : "서울로미디어캔버스의 2026년 두 번째 전시는 무르익은 여름의 풍경 속에서 도시와 자연, 그리고 청년 창작자들의 다양한 시선을 담아 관람객을 맞이합니다. 이번 전시는 네이처프로젝트전과 대학협력전으로 구성되며, 변화하는 도시의 풍경과 자연의 순환, 그리고 이를 바라보는 새로운 세대의 감각을 미디어아트로 선보입니다.",
        // "exhibit_2_introduce_sub" : "*특정 지역이나 환경을 대표하면서 사람들의 관심과 보호의식을 이끌어내기 위해 선정된 상징적인 생물종",
        // "exhibit_2_explain_name_1" : "시작의 근원",
        "exhibit_2_explain_1" : "대학협력전은 미래의 미디어아트 분야를 이끌어갈 대학생 작가들의 참신한 상상력과 실험적인 시선을 소개합니다. 서울의 일상과 계절의 감각, 전통과 현대, 개인의 기억과 감정을 다채로운 방식으로 해석한 작품들은 공공 미디어 플랫폼을 통해 시민들과 만나며 새로운 공감의 장을 만들어냅니다.",
        // "exhibit_2_explain_name_2" : "모먼트 서울",
        "exhibit_2_explain_2" : "네이처 프로젝트전은 자연이 품고 있는 생명력과 시간의 흐름, 그리고 회복과 순환의 가치를 탐구합니다. 사계절의 변화와 생태계의 회복, 일상 속 자연의 기록, 그리고 미시적 생명에서 거대한 우주로 이어지는 연결성을 다룬 작품들은 자연을 바라보는 다양한 관점을 제시하며 관람객들에게 사유의 시간을 선사합니다.",
        // "exhibit_2_explain_name_3" : "한강 네이처",
        // "exhibit_2_explain_3" : "한강 네이처는 서울의 비전인 ‘매력’을 상징하며, 자연이 살아 숨 쉬는 한강 노들섬의 생태를 미디어아트로 풀어낸 자연도감입니다.\n맹꽁이를 주인공으로 한 옴니버스 애니메이션으로, 새로운 터전을 찾아가는 여정을 통해 노들섬의 생태와 계절의 변화, 그리고 서울과 한강의 다양한 모습을 전합니다.",
        
        "link_button_text" : "영상 보러가기",

        "exhibit_name_1" : "대학협력전",
        "exhibit_name_2" : "네이처 프로젝트전",

        "exhibit_list_1" : "유영",
        "exhibit_list_2" : "하루가 구워지는 곳",
        "exhibit_list_3" : "잠상",
        "exhibit_list_4" : "마음의 꽃잎",
        "exhibit_list_5" : "네모난 방 안에서 네모난 여름",
        "exhibit_list_6" : "여름휴가",
        "exhibit_list_7" : "말",
        "exhibit_list_8" : "각자의 방식으로",
        "exhibit_list_9" : "창 너머",
        "exhibit_list_10" : "달콤한 여름",
        "exhibit_list_11" : "자개가 펼처지는 순간",
        "exhibit_list_12" : "소원",
        "exhibit_list_13" : "유월의 하루",
        "exhibit_list_14" : "동화 이야기",
        "exhibit_list_15" : "빛의 깊은 물결",
        "exhibit_list_16" : "천문",
        "exhibit_list_17" : "서울 소울메이트",
        "exhibit_list_18" : "경계",
        "exhibit_list_19" : "흐르는 서울",
        "exhibit_list_20" : "서울을 가로지르는 바람",
        "exhibit_list_21" : "침입",
        
        "exhibit_list_22" : "사계",
        "exhibit_list_23" : "오랜만이야!",
        "exhibit_list_24" : "오늘도, 그 산은",
        "exhibit_list_25" : "세포에서 은하까지",


        "exhibit_artist_name_1" : "황세희",
        "exhibit_artist_name_2" : "전수아",
        "exhibit_artist_name_3" : "박지현",
        "exhibit_artist_name_4" : "김서운",
        "exhibit_artist_name_5" : "권예지",
        "exhibit_artist_name_6" : "김소정",
        "exhibit_artist_name_7" : "박규리",
        "exhibit_artist_name_8" : "이여진",
        "exhibit_artist_name_9" : "양이삭",
        "exhibit_artist_name_10" : "최수빈",
        "exhibit_artist_name_11" : "강지수",
        "exhibit_artist_name_12" : "이혜진",
        "exhibit_artist_name_13" : "이채현",
        "exhibit_artist_name_14" : "원유경",
        "exhibit_artist_name_15" : "이소형",
        "exhibit_artist_name_16" : "김단아\n이채린\n정유경",
        "exhibit_artist_name_17" : "김나현\n김도향\n황신영",
        "exhibit_artist_name_18" : "권수진\n김지연\n박예림",
        "exhibit_artist_name_19" : "송찬영\n유지혜\n차시은",
        "exhibit_artist_name_20" : "진가려\n추운가\n리신",
        "exhibit_artist_name_21" : "김송림\n남유연\n은수안\n조나연",
        
        "exhibit_artist_name_22" : "김영우",
        "exhibit_artist_name_23" : "나나",
        "exhibit_artist_name_24" : "장철원",
        "exhibit_artist_name_25" : "최인종",

        "art_list_1" : "<유영(游泳)>",
        "art_list_2" : "<하루가 구워지는 곳>",
        "art_list_3" : "<잠상(潛像)>",
        "art_list_4" : "<마음의 꽃잎>",
        "art_list_5" : "<네모난 방 안에서 네모난 여름>",
        "art_list_6" : "<여름휴가>",
        "art_list_7" : "<말>",
        "art_list_8" : "<각자의 방식으로>",
        "art_list_9" : "<창 너머>",
        "art_list_10" : "<달콤한 여름>",
        "art_list_11" : "<자개가 펼처지는 순간>",
        "art_list_12" : "<소원>",
        "art_list_13" : "<유월의 하루>",
        "art_list_14" : "<동화 이야기>",
        "art_list_15" : "<빛의 깊은 물결>",
        "art_list_16" : "<천문>",
        "art_list_17" : "<서울 소울메이트>",
        "art_list_18" : "<경계>",
        "art_list_19" : "<흐르는 서울>",
        "art_list_20" : "<서울을 가로지르는 바람>",
        "art_list_21" : "<침입>",
        
        "art_list_22" : "<사계>",
        "art_list_23" : "<오랜만이야!>",
        "art_list_24" : "<오늘도, 그 산은>",
        "art_list_25" : "<세포에서 은하까지>",


        "artist_name_1" : "황세희",
        "artist_name_2" : "전수아",
        "artist_name_3" : "박지현",
        "artist_name_4" : "김서운",
        "artist_name_5" : "권예지",
        "artist_name_6" : "김소정",
        "artist_name_7" : "박규리",
        "artist_name_8" : "이여진",
        "artist_name_9" : "양이삭",
        "artist_name_10" : "최수빈",
        "artist_name_11" : "강지수",
        "artist_name_12" : "이혜진",
        "artist_name_13" : "이채현",
        "artist_name_14" : "원유경",
        "artist_name_15" : "이소형",
        "artist_name_16" : "김단아 이채린 정유경",
        "artist_name_17" : "김나현 김도향 황신영",
        "artist_name_18" : "권수진 김지연 박예림",
        "artist_name_19" : "송찬영 유지혜 차시은",
        "artist_name_20" : "진가려 추운가 리신",
        "artist_name_21" : "김송림 남유연 은수안 조나연",
        
        "artist_name_22" : "김영우",
        "artist_name_23" : "나나",
        "artist_name_24" : "장철원",
        "artist_name_25" : "최인종",
        
        "art_explain_1" : "⟨유영(游泳)⟩은 코스모스 꽃밭 아래에서 하늘을 바라보며, 천천히 흐르는 구름과 바람에 흔들리는 꽃들의 움직임을 생동감 있게 담아낸 작품이다.\n6월의 초여름은 생명이 가장 선명하게 숨 쉬는 계절이다.\n푸른 하늘 아래 펼쳐진 코스모스 들판에 누워, 마치 여름 속을 유영하듯 그 순간의 공기와 흐름을 온전히 체감하게 된다.\n\n빠르게 흘러가는 도심의 일상 속에서 잠시 걸음을 멈추고, 현대인들이 무심히 지나치던 하늘과 계절의 감각에 천천히 몰입할 수 있도록 한다.\n\n잔잔히 흐르는 6월의 순간을 유영하듯.",
        "art_explain_2" : "빠르게 흘러가는 서울의 일상 속에서 사람들은 끊임없이 움직이며 여유를 잃기 쉽습니다. 저 역시 바쁜 생활 속에서 잠시 쉬어갈 시간이 부족하다고 느꼈고, 이러한 경험을 바탕으로 따뜻한 휴식의 공간을 표현하고자 했다.\n그래서 현실과 다른 속도로 시간이 흐르는 ‘쥐들의 애플파이 가게’를 컨셉으로 설정했다. 작은 쥐들이 천천히 애플파이를 굽고 피크닉을 즐기는 모습을 통해 느리고 포근한 시간을 담았으며, 굴러온 사과에 놀라 분주하게 움직이는 장면으로 잔잔한 일상 속 작은 활기를 더했다.\n이 작품이 바쁜 일상 속에서 잠시 멈춰 여유와 힐링을 떠올릴 수 있는 작은 쉼표가 되기를 바란다.",
        "art_explain_3" : "잠상(潛像)'은 사진 용어로, 필름에 기록되어 있지만 아직 눈에 보이지 않는 이미지를 의미한다. 이 작품은 이러한 개념을 꿈과 기억의 이미지에 연결하여 표현한 패턴 기반 미디어 작업이다.\n영상 속 꽃의 형태와 패턴은 반복되고 확장되며 끊임없이 변화한다. 흐릿한 형상은 잠시 선명하게 드러났다가 다시 사라지고, 서로 다른 이미지들은 겹쳐지며 새로운 장면을 만들어낸다. 반복적으로 변화하는 패턴은 꿈속에서 떠오르는 기억의 조각들과 감정의 흐름을 상징한다.\n우리는 꿈속에서 현실의 기억과 감정, 익숙한 장면들이 예상치 못한 모습으로 나타나는 경험을 하곤 한다. 작품은 이러한 꿈의 특성을 패턴과 움직임으로 시각화하며, 보이지 않던 이미지가 떠오르고 사라지는 순간을 담아낸다.\n관람자는 끊임없이 변화하는 형상과 흐름 속에서 꿈과 기억의 잔상을 따라가며, 자신만의 감정과 상상을 마주하게 된다.",
        "art_explain_4" : "눈에 보이지 않는 감정의 흐름을 유기적인 꽃의 형태와 부드러운 움직임으로 표현한 미디어 아트 작품이다.\n우리는 일상 속에서 기쁨, 불안, 설렘, 평온 등 다양한 감정을 경험하며 살아간다. 하지만 감정은 하나의 형태로 정의되지 않고 서로 섞이며 끊임없이 변화한다.\n이 작품은 이러한 감정의 흐름을 추상적인 꽃의 형상과 자연스러운 움직임으로 시각화하였다.\n꽃의 형태는 피어나고 흩어지기를 반복하며 감정이 생성되고 변화하는 과정을 상징한다. 서로 겹쳐지고 이어지는 유기적인 움직임은 감정이 시간의 흐름 속에서 변화하고 순환하는 모습을 담고 있다. 또한 형태와 질감이 만들어내는 부드러운 흐름을 통해 눈에 보이지 않는 감정의 움직임을 표현하고자 하였다.\n끊임없이 변화하는 꽃의 형상은 복잡한 감정들이 하나의 흐름 안에서 피어나고 사라지는 과정을 보여주며, 형태 없는 내면의 감정을 시각적으로 풀어낸다.",
        "art_explain_5" : "여름하면 생각나는 바다, 바쁜 나날들로 직접 가지 못해도 방 안에서 수족관 장난감에 담긴 바다를 즐길 수 있다.\n작고 네모난 영역에서 전개되는 바다를 멍하니 바라보다 보면 시간 가는 줄 모른다.\n마치 서울로 미디어의 네모난 스크린에서, 네모난 방 안에 있는, 네모난 수족관을 바라보는 것처럼.",
        "art_explain_6" : "여름 휴가는 답답하고 빠르게 흘러가는 도심의 소란스러운 일상 속에서, 온전한 해방감을 찾아 떠나는 여정을 담은 영상이다. 네온사인으로 가득한 삭막한 도시의 야경을 지나 화면이 전환되면, 시원한 칵테일 한 잔과 함께 에메랄드빛 푸른 바다가 눈앞에 펼쳐진다.\n야근과 힘든 일상 속에서 벗어나 누구나 한 번쯤 꿈꾸는 이국적이고 평화로운 공간으로 이동한다. 낮과 밤을 관통하며 펼쳐지는 휴양지의 풍경은 갇혀 있던 답답함을 해소하고 꿈꾸는 것 같은 공간으로 넘어가 지친 일상을 벗어난다는 해방감을 선사한다.",
        "art_explain_7" : "2026년 병오년, 말의 해를 맞아 다양한 생김새의 말들이 각자의 걸음으로 화면을 가로지르는 영상을 제작했다.\n영상 속 말들은 반복되는 일상 속에서도 각자의 방향을 향해 끊임없이 움직이며 살아가는 우리들의 모습을 상징한다. 어떤 말은 빠르게 달리고, 어떤 말은 천천히 걸어간다. 크기와 형태, 속도는 모두 다르지만 모든 말들은 저마다의 리듬으로 앞으로 나아간다.\n\n우리는 종종 타인의 속도와 방향을 기준 삼아 스스로를 비교하며 살아간다. 하지만 이 작품은 서로 다른 모습과 속도를 가진 존재들이 같은 화면 안에서 함께 움직이는 모습을 통해, 각자의 방식대로 살아가는 삶 자체에 의미가 있음을 이야기하고자 했다.\n영상 속 말들은 정해진 목적지 없이 계속해서 움직이다. 이는 바쁘게 흘러가는 현대 사회 속에서 끊임없이 앞으로 나아가야 하는 우리의 모습과 닮아\n있습니다. 모두가 같은 길을 걷고 있지는 않지만, 각자의 자리에서 자신만의 방향을 향해 묵묵히 나아가고 있다는 점만큼은 같다.\n이 작품은 서로 다른 속도와 형태를 가진 존재들이 한 공간 안에서 함께 흐르는 장면을 통해, \n각자의 삶의 방향성과 움직임에 대해 다시 바라보고자 제작한 작업이다.",
        "art_explain_8" : "도시를 살아가는 젤리곰들은 모두 같은 모습으로 태어났지만, 각자가 마주한 환경에 따라 전혀 다른 삶을 살아간다.\n뜨거운 빛 아래 녹아내리기도 하고, 위험을 피해 움직이기도 하며, 때로는 변화한 모습 그대로 새로운 환경에 적응하기도 한다.\n\n이 작품은 도시라는 공간을 축소된 사회로 바라보며, 같은 조건에서 시작하더라도 환경에 따라 달라지는 존재들의 다양한 생존 방식을 표현한다.",
        "art_explain_9" : "밤이 내려앉은 작은 방 안, 무료함에 잠겨 있던 소년 앞에 작은 종이비행기 하나가 날아든다. 소년은 망설임 없이 종이비행기를 따라 움직이고, 결국 창밖으로 몸을 던질 만큼 충동적인 행동을 보인다.\n그 순간, 곁에 있던 인물은 급하게 소년을 붙잡으며 짧은 위기의 순간을 함께 마주하게 된다.\n본 작품은 ʻPROJECT : SHOMA’ 세계관을 기반으로 제작된 3D 아나몰픽 미디어파사드 영상으로, 두 인물간의 관계성과 행동으로 드러나는 성격 차이, 감정의 흐름을\n짧은 서사 안에 담아내고자 하였다.\n영상은 지루함에서 시작해 호기심, 몰입, 긴장, 안도감, 여운으로 이어지는 감정 구조를 기반으로 구성되었으며, 고정된 카메라와 원테이크 형식을 통해 공간의 연속성과\n몰입감을강조하였다. 또한 배경 속 액자와 도시 풍경등 다양한 시각적 요소를 통해 작품 세계관의 일부를 암시적으로 표현하였다.",
        "art_explain_10" : "'여름'과 '동심'을 키워드로 하여 도심의 공간을 청량한 상상들로 환기시킨다.\n\n중력을 거슬러 공중을 가르는 거대한 미끄럼틀, 떠다니는 구름을 만져보고 솜사탕처럼 맛보는 행위, 수많은 풍선들을 타고\n하늘을 유영하는 기구, 아이스크림으로 된 벽을 맛보기도 하는 등 어릴 적 누구나 한 번쯤 꿈꾸었던 환상을 그린다.\n\n여름의 파란 하늘과 그 속을 유영하는 곰젤리들의 움직임은 현재 어른이 되어야할 우리들이 보여야하는 정적인 어른스러운\n행동들과 대비된다. 작품을 통해 달콤했던 어릴적 상상들로 해방감을 맛보고 시원한 휴식이 되기를 바란다.",
        "art_explain_11" : "‘자개가 펼쳐지는 순간’은 한국 전통 자개를 하나의 세계를 품은 표면으로 바라보는 데서 출발한다. 자개 문양은 공예품 위에 고정된 무늬처럼 보이지만, 그 안에는 빛의 방향에 따라 달라지는 색, 겹겹이 쌓인 결에 따라 다르게 드러나는 이미지가 존재한다 이러한 자개의 특성을 바탕으로, 문양 안에 잠재되어 있던 세계가 현실의 공간으로 확장되는 순간을 상상한다. 자개는 빛과 움직임을 통해 생명력을 얻는 매개체가 되어 풍경과 생명, 기억을 품은 하나의 공간으로 보여줍니다.\n\n따라서 ‘자개가 펼쳐지는 순간’은 자개 문양 안에 숨겨진 세계를 현실로 불러내고 다시 문양으로 회귀시킨다. 고정된 문양은 잠시 움직이는 풍경이 되고, 표면은 하나의 공간으로 확장되며, 마지막에는 다시 자개의 결 안으로 돌아가 빛과 시간의 흔적으로 남습니다.",
        "art_explain_12" : "어린 시절 우리는 생일 케이크의 촛불 앞에서 순수한 마음으로 소원을 빌었다. 그 소원은 때로는 사소하고 엉뚱했지만, 미래를 향한 솔직한 꿈과 희망이 담겨 있었다.\n하지만 시간이 흘러 어른이 된 우리는 현실의 무게 속에서 점차 물질적이고 현실적인 목표를 우선하게 된다. 그 과정에서 어린 시절 품었던 순수한 바람과 꿈들은 기억 속 깊은 곳에 묻혀버리기도 한다.\n본 작품은 잊고 지냈던 어린 시절의 소원을 다시 떠올리게 하며, 현재의 삶이 그때의 꿈과 얼마나 맞닿아 있는지 되묻는다. 촛불을 끄기 전 두 손을 모으던 순간의 설렘을 통해, 관람자가 자신의 내면에 남아 있는 소망과 가능성을 돌아보도록 유도한다.\n이 작품이 잊혀진 소원의 불씨를 다시 밝히고, 현재의 나를 다정하게 성찰하는 작은 계기가 되기를 바란다.",
        "art_explain_13" : "이 작품은 우리 전통 명절인 단오의 풍경을 바탕으로, 과거 사람들의 하루를 시간의 흐름에 따라 풀어낸 2D 미디어 아트이다.\n아침의 고요함에서 시작해 해가 저물고 밤이 찾아오기까지, 단오날의 다양한 순간들을 하나의 긴 풍경처럼 이어 담아내고자 했다.\n단오는 모내기를 마친 뒤 풍년과 안녕을 기원하며 잠시 삶을 쉬어가던 날이었다. 사람들은 창포물에 머리를 감고, 그네를 타고, 자연 속에서 서로 어울리며 계절의 변화와 삶의 안녕을 느꼈다. 작품 속 장면들은 이러한 단오의 풍습과 정서를 작은 움직임과 요소들로 풀어내며, 잊혀져가는 과거의 시간을 시각적으로 기록한다.\n특히 화면 전체가 천천히 흘러가는 구조를 통해, 단순한 풍경 재현이 아닌 ‘흘러가는 하루의 감각’을 전달하고자 했다.\n안개처럼 번지는 배경과 반복되는 움직임들은 기억 속 어딘가에 남아있는 옛 풍경의 잔상을 표현하며, 관람자로 하여금 잠시 과거의 시간 속을 거니는 듯한 경험을 마주하게 한다.",
        "art_explain_14" : "고전 서사인 오즈의 마법사와 한국 전래동화 심청전을 결합하여, 바다에 빠진 심청이가 낯선 세계에서 눈을 뜨는 순간을 영상으로 표현했다.\n작품 속 심청이는 드넓은 산과 다양한 물고기들을 마주하며 현실과 환상이 뒤섞인 공간을 지나간다. 화면은 뒤로 갈수록 색감이 변화하며 또 다른 세계의 모습을 드러내고, 동양적인 분위기와 판타지적인 이미지를 함께 담아냈습니다.\n이 작업은 추락이라는 상황을 단순히 부정적인 순간으로 바라보지 않습니다. 아래로 떨어지는 과정 속에서도 새로운 풍경과 빛을 만나듯, 불안과 흔들림 또한 삶 속에서 지나가는 하나의 과정이자 아름다운 순간이 될 수 있음을 이야기하고자 했다.",
        "art_explain_15" : "The Shimmering Deep: Wave of Life\n우리가 마주한 스크린 속에는 빛과 색이 빚어낸 가장 순수하고 아름다운 바다가 흐르고 있다.\n몽환적인 파스텔톤으로 물든 물결은 자연이 가진 가장 부드러운 색채를 보여주고, 그 위로 부서지는 하얀 빛줄기는 찰나의 순간을 아름답게 밝힌다. 이 평화로운 공간을 가득 채우는 것은 역동적으로 살아 움직이는 물고기들이다. 저마다의 색을 품고 무리 지어 유영하는 움직임은 마치 자연이 추는 하나의 거대한 춤처럼 다가온다.\n복잡한 생각을 잠시 내려놓고, 자연이 만들어내는 감각적인 색채와 생동감 넘치는 생명의 에너지를 있는 그대로 느끼며 잔잔하게 일렁이는 물결을 따라 걷다 보면, 마음속 가득 기분 좋은 해방감이 채워질 것이다.",
        "art_explain_16" : "'천문'은 하늘에서 일어나는 일체의 자연 현상과 이를 연구하는 학문을 뜻한다.\n\n천문을 연구하듯 서울의 하늘을 새로운 시선으로 바라보며, 도심과 미디어가 하나의 풍경으로 어우러지는 밤하늘을 그린다. 검은 먹이 종이 위로 스며들듯 밤하늘 위에는 수묵이 퍼지고, 흩어진 별들은 점과 선이 되어 서로 연결된다. 그렇게 서울의 밤하늘에 별자리처럼 이어진 한 폭의 수묵화가 펼쳐진다.",
        "art_explain_17" : "서울의 다채로움, 함께여서 든든한 상생\n빠르게 돌아가는 서울 사회 속에서 사람들은 각자의 삶에만 집중한 채 살아간다. 같은 도시 안에 있지만 서로 연결되지 못하고 단절된 개인으로 존재한다. 그러나 서울은 다양한 사람들이 함께 살아가는 도시이며, 서로 다른 개성과 가치가 모일 때 더욱 큰 힘을 만들어낼 수 있다.\n해치와 해치프렌즈는 이러한 서울의 모습을 담아낸다. 단절되어 있던 존재들이 서로 연결되고 어우러지는 과정을 통해 서울의 다채로운 매력과 상생의 가치를 표현하였다. 서로 다른 사람들이 함께할 때 더욱 든든한 공동체가 만들어진다는 메시지를 캐릭터로 밝고 친근하게 전달하고자 한다.",
        "art_explain_18" : "전통은 과거에 머무는 것이 아니라, 현재를 통과해 미래로 이어지는 통로이다.\n'경계'는 한국의 전통 요소의 아름다움과 가치를 현대적으로 재해석하여 서울의 리듬을 시각화한다.\n반복되는 패턴은 우리의 일상과 도시의 움직임을 담아내며,\n복잡하고 어지러운 일상 속 잠시 멈춰 주변을 바라보게 한다.\n이를 통해 관람자는 전통이 지닌 고요한 색감과 절제된 아름다움을 경험하게 된다.\n이들은 경계가 아닌 통로로 작용하며, 전통과 현대, 내부와 외부를 넘나드는 경험을 만들어낸다.",
        "art_explain_19" : "우리는 매일 서울을 지나친다.\n빠르게 스쳐가는 창밖의 풍경 속에는 각기 다른 표정의 서울이 흐른다.\n\n본 작품은 지하철 창문 너머로 마주한 서울의 랜드마크와 도시의 풍경을 따라가며 하루를 담아낸다. 익숙하지만 쉽게 머무르지 못했던 서울의 아름다운 풍경을 잠시라도 천천히 바라보는 여유를 전하고자 한다.",
        "art_explain_20" : "‘바람’을 주제로 한 이 멀티미디어 아트 작품은 다양한 시선을 통해 서울의 다채로운 풍경을 표현한다. 화면은 바람의 움직임을 따라 자연스럽게 서울역, 남산타워, 경복궁 등 서울의 대표적인 명소들을 지나간다. 바람은 꽃잎으로 형상화되며, 꽃잎이 지나가는 곳마다 도시의 풍경은 동양 전통 회화의 분위기를 담은 장면으로 변화한다.\n작품의 색채와 구도는 한국 전통 회화인 「일월오봉도」에서 영감을 받아, 해와 달, 산과 강, 자연의 상징적 요소들을 현대적인 시각 언어로 재해석하였다. 관람자는 익숙한 서울의 풍경을 새로운 예술적 경관으로 경험하며, 도시와 자연, 전통과 현대가 조화롭게 어우러지는 시각적 향연을 느낄 수 있다.\n또한 서울을 처음 방문하는 관광객들에게는 이 작품이 하나의 도시 여행 지도로서 기능하며, 서울의 주요 관광 명소를 소개하는 역할도 수행한다.",
        "art_explain_21" : "침입은 주체가 뒤바뀌는 순간이다.\n\n인간은 자연을 점유하고, 그 위에 건물을 구축한다.\n그러나 자연은 사라진 것이 아니라, 다른 방식으로 그 공간에 잔존한다.\n이 프로젝트는 인간이 만든 구조 내부에서 드러나는 자연의 흔적을 통해,\n공간의 주체가 누구인가에 대한 질문을 제기한다.\n\n침입은 단방향의 사건이 아니다.\n인간은 자연을 침범하고, 자연은 다시 인간의 공간으로.\n\n침입은 반복된다.",

        "art_explain_22" : "민화에 등장하는 소재들을 현대적으로 재해석하여 표현하고, 사계의 흐름으로 구성한 영상이다. 영상은 꽃과 새가 등장하는 화조도가 봄으로 표현되어 시작된다. 이어서 비가 내리며 피어나는 수국과 그 주변을 맴도는 나비는 꽃과 벌레의 조합인 초충도를 상징하며, 봄과 여름 사이의 시기를 오묘한 분위기로 표현했다. 수국이 지며 자라나는 연잎과 연꽃, 어느 순간 날아드는 잠자리들은 수국과 나비의 조합과 마찬가지로 초충도를 상징하지만 한여름을 지나 다가오는 가을의 암시가 느껴지는,시간의 흐름을 달리 해석하게 한다.\n어느덧 무르익은 논밭과 벼,귀뚜라미,흩날리는 낙엽은 완연한 가을이 왔음을 알린다. 그리고 그 속에 두 마리의 학이 등장하고,학을 따라 비행하자 첩첩산중이 보여 진다. 학과 산은 장생도의 요소들이며,흩날리는 눈과 함께 겨울산의 풍경이 길고 긴 겨울처럼 끝없이 펼쳐지며 영상이 마무리된다.\n염원을 상징하는 민화의 요소들이 사계절로 구성된 것처럼 시간의 흐름마다 안정과 평화,소망이 이루어지기를 바라는 마음이다.",
        "art_explain_23" : "〈오랜만이야!〉는 가뭄으로 메말랐던 숲에 비가 내리며 생명들이 다시 살아나는 과정을 담은 그림 기반 영상 작품이다. 그림 같은 이미지와 붓터치의 느낌을 살려 숲의 변화를 자연스럽게 보여준다. 갈라진 땅과 조용한 숲에서 시작해, 첫 빗방울이 떨어지면서 생명은 조금씩 움직이기 시작한다. 비는 숲을 되살리는 역할을 하며, 다양한 생명들이 서로 연결되어 있음을 보여준다. 이 작품은 자연이 다시 살아나는 모습과 함께 우리가 잊고 지냈던 자연의 감각을 다시 느끼게 한다.",
        "art_explain_24" : "3년 동안 거의 매일 아침, 같은 자리에서 산과 하늘을 바라보며 사진을 찍었다. 처음부터 어떤 목적이나 의도가 있었던 것은 아니다. 매일 지나치던 그 자리에서 바라본 풍경이 눈에 남았을 뿐이었다.\n\n같은 장소에서 같은 방향을 바라보았지만, 그곳은 항상 같은 모습이 아니었다. 날씨와 계절, 빛의 변화와 공기의 밀도에 따라 산과 하늘은 끊임없이 다른 모습을 드러냈다. 그 변화는 한 장의 사진만으로는 쉽게 보이지 않았지만, 시간이 쌓이면서 비로소 하나의 흐름을 만들어냈다.\n\n이 영상은 그렇게 모은 사진들을 페이드 방식으로 연결해 만든 것이다. 익숙한 풍경 속에 천천히 스며든 시간의 흐름, 그리고 그 안에서 일어난 변화를 시각적으로 담아내고자 했다.",
        "art_explain_25" : " 본 작품은 정형화된 인류의 회색 도시 문명 속에서 태동한 자연의 원초적 생명력을 통해, 미시적 세포와 거대한 대우주가 지닌 유기적 관계성과 영원한 순환을 탐색한다. 차가운 인공적 그리드를 깨뜨리고 솟아오른 다채로운 오브제들은 자연의 질서를 닮아가며 초현실적인 생태계로 순환하고, 이내 피고지며 만개해 나가는 꽃과 식물 줄기, 일렁이는 구체의 형태로 생명의 역동적인 에너지를 묘사한다.\n 이 미시적인 생명의 에너지는 점차 거대한 성운과 은하라는 거시적 우주 공간으로 확장하고 폭발하며, 자연의 모든 존재가 단절 없이 촘촘하게 연결되어 있음을 암시한다.\n앰비언트 사운드의 평안함과 함께 전개되는 이 시각적 퍼포먼스는 가장 작은 세포에서 시작해 무한한 대우주의 순환 속으로 환원되는 존재의 궤적을 따라가게 하고,\n이를 통해 도심 속 관객들에게 화면을 넘어선 대자연의 색채적 아름다움과 시각적 심상의 유기적 관계에 대한  상상을 선사하고자 한다.",

        "time_table_title" : "전시 순서 안내",
        "time_table_title_1" : "예술",
        "time_table_title_2" : "동행",
        "time_table_title_3" : "매력",
        "time_table_title_sub_1" : "시작의 근원",
        "time_table_title_sub_2" : "모먼트 서울",
        "time_table_title_sub_3" : "한강 네이처",
        "time_table_art_1" : "1. 이돈아 〈무한한 행복을 향한 여정〉",
        "time_table_art_2" : "2. 최성록 〈서울하늘변신구름많음〉", 
        "time_table_art_3" : "",
        "time_table_art_4" : "3. 서울응원 봄메시지",
        "time_table_art_5" : "4. 해치와 서울나들이",
        "time_table_art_6" : "5. 꼬마 맹꽁이의 모험",
        "time_table_art_7" : "6. 이돈아 〈화조도〉",
        "time_table_art_8" : "7. 최성록 〈기원의 협곡〉",
        "time_table_art_9" : "",
        "time_table_art_10" : "8. 서울응원 봄메시지",
        "time_table_art_11" : "9. 해치와 서울나들이",
        "time_table_art_12" : "10. 꼬마 맹꽁이의 모험",

        "directions_title" : "오시는 길",

        "directions_explain_title_1" : "지하철",
        "directions_explain_title_2" : "버스",
        "directions_explain_title_3" : "자선 버스",

        "directions_explain_1" : "1호선\n용산역 5번출구 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004)\n노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차 -\n노들섬 동측 주차장 방면 진입로 통해 입장\n\n4호선\n신용산역 3번출구 - 도보 100m 위치 신용산역 정류장(03-004) -\n용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차 -\n노들섬 동측 주차장 방면 진입로 통해 입장\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동 - \n노들섬 동측 주차장 방면 진입로 통해 입장\n\n\n",
        "directions_explain_2" : "간선 버스\n150, 151, 152, 500, 504, 506,\n507, 605, 750A, 750B, 751, 752",
        "directions_explain_3" : "지선버스\n6211\n각 버스 하차 후 노들섬 동측 주차장 방면 진입로 통해 입장\n\n한강버스\n여의도 - 압구정 사이 구간에서 관람 가능",
    },
    en : {
        "index_button_introduce" : "About Seoullo Media Canvas",
        "index_button_schedule" : "Schedule",
        "index_button_exhibit" : "Exhibition Introduction",
        "index_button_exhibit_sub" : "",
        // "index_button_art_1" : "DongHaeng(empathy) ",
        // "index_button_art_1_sub" : " Moment Seoul",
        // "index_button_art_2" : "MaeRyeok(charming)",
        // "index_button_art_2_sub" : " Hangang Nature",
        // "index_button_directions" : "Location",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        // "atelier_nodeul_name" : "아뜰리에 노들",
        // "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        // "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        // "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<Atelier Nodeul 2026 1st Exhibition : The Origin of All Beginnings> Timeline",
        "schedule_explain_date" : "Exhibition Period | March 22, 2026 (Fri) – July 31, 2026 (Fri)",
        "schedule_explain_pos" : "Venue | Media Façade under the southern pier of Hangang Bridge, \n             Nodeul Island",
        "schedule_explain_pos_detail" : "",
        "schedule_explain_time" : "Screening Hours | 20:00–22:00 (Screened every hour on the hour)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        // "exhibit_intro_title" : "Exhibition Introduction",        
        // "exhibit_introduce_name" : "Atelier Nodeul 2026 1ST EXHIBITION : The Origin of All Beginnings",
        "exhibit_introduce" : "Seoullo Media Canvas is a dedicated media art platform that expands the boundaries of media art by continuously presenting media art and video-based artworks created through electronic light, offering citizens opportunities to appreciate and engage with contemporary digital art.",
        // "exhibit_introduce_sub" : "",
        // "exhibit_explain_name_1" : "The Origin of All Beginnings",
        // "exhibit_explain_1" : "'The Origin of All Beginnings' is a media art exhibition on Nodeul Island, where the lights of the city and the waters of the Hangang River come together.\n\nThrough the dynamic works of two media artists, the exhibition explores moments of origin and creation while highlighting the artistic charm of Nodeul Island and the new possibilities of the Hangang River.",
        // "exhibit_explain_name_2" : "Moment Seoul",
        // "exhibit_explain_2" : "'Moment Seoul' highlights one of Seoul's core values: a compassionate city that walks alongside the vulnerable.\nThrough Spring Message of Support from Seoul, it delivers messages of encouragement to citizens facing new beginnings, while Haechi’s Seoul Journey follows a journey from Nodeul Island to the skies above Seoul, set against the scenery of Nodeul Island and the Hangang River.",
        // "exhibit_explain_name_3" : "Hangang Nature",
        // "exhibit_explain_3" : "'Hangang Nature' represents Seoul's vision of 'Charm', presenting a media-art nature archive of the living ecology of Nodeul Island and the Hangang River.\n\nThrough an omnibus animation featuring the \"Maengkkongi\" the boreal digging frog, as its main character, the work follows a journey in search of a new home, conveying the island's ecology, seasonal changes, and the diverse landscapes of Seoul and the Hangang River.",
        
        "exhibit_2_intro_title" : "Exhibition Introduction",        
        "exhibit_2_introduce_name" : "2nd Exhibition 07.01.-09.19.",
        "exhibit_2_introduce" : "The second exhibition of 2026 at Seoullo Media Canvas welcomes visitors with diverse perspectives on the city, nature, and emerging young creators set against the backdrop of midsummer. The exhibition consists of two sections: the Nature Project Exhibition and the University Collaboration Exhibition, presenting media artworks that explore the evolving urban landscape, the cycles of nature, and the fresh perspectives of a new generation.",
        // "exhibit_2_introduce_sub" : "",
        // "exhibit_2_explain_name_1" : "The Origin of All Beginnings",
        "exhibit_2_explain_1" : "The University Collaboration Exhibition showcases the creativity and experimental vision of university students who represent the future of media art. Through works that reinterpret everyday life in Seoul, the changing seasons, tradition and modernity, as well as personal memories and emotions, the exhibition creates new opportunities for connection and empathy between young artists and the public through a civic media art platform.",
        // "exhibit_2_explain_name_2" : "Moment Seoul",
        "exhibit_2_explain_2" : "The Nature Project Exhibition explores the vitality of nature, the passage of time, and the values of renewal and cyclical change. Addressing themes such as the changing seasons, ecological restoration, everyday observations of nature, and the interconnectedness between microscopic life and the vast universe, the featured works offer diverse perspectives on the natural world while inviting visitors to pause, reflect, and contemplate.",
        // "exhibit_2_explain_name_3" : "Hangang Nature",
        // "exhibit_2_explain_3" : "'Hangang Nature' represents Seoul's vision of 'Charm', presenting a media-art nature archive of the living ecology of Nodeul Island and the Hangang River.\n\nThrough an omnibus animation featuring the \"Maengkkongi\" the boreal digging frog, as its main character, the work follows a journey in search of a new home, conveying the island's ecology, seasonal changes, and the diverse landscapes of Seoul and the Hangang River.",
        
        "link_button_text" : "Watch Video",

        "exhibit_name_1" : "The University Collaboration Exhibition",
        "exhibit_name_2" : "Nature Project Exhibition",

        "exhibit_list_1" : "Swimming",
        "exhibit_list_2" : "Where a day is baked",
        "exhibit_list_3" : "LATENT IMAGE",
        "exhibit_list_4" : "Petals of the Mind",
        "exhibit_list_5" : "A Square Summer in a Square Room",
        "exhibit_list_6" : "summer vacation",
        "exhibit_list_7" : "The Horse",
        "exhibit_list_8" : "Adapting in Our Own Ways",
        "exhibit_list_9" : "BEYOND THE WINDOW",
        "exhibit_list_10" : "Sweet Summer",
        "exhibit_list_11" : "The Moment Nacre Unfolds",
        "exhibit_list_12" : "Make A Wish",
        "exhibit_list_13" : "A Day in June",
        "exhibit_list_14" : "A Fairy Tale",
        "exhibit_list_15" : "Shimmering deep wave",
        "exhibit_list_16" : "CheonMun",
        "exhibit_list_17" : "Seoul Soulmates",
        "exhibit_list_18" : "Threshold",
        "exhibit_list_19" : "Flowing Seoul",
        "exhibit_list_20" : "Wind Across Seoul",
        "exhibit_list_21" : "Intrusion",
        
        "exhibit_list_22" : "The four seasons",
        "exhibit_list_23" : "Hello Again, Rain",
        "exhibit_list_24" : "Today, That Mountain",
        "exhibit_list_25" : "Connection : From Cell to Galaxy",


        "exhibit_artist_name_1" : "Hwang Se Hee",
        "exhibit_artist_name_2" : "Jeon Soo Ah",
        "exhibit_artist_name_3" : "Park Ji Hyeon",
        "exhibit_artist_name_4" : "Kim Seo Yun",
        "exhibit_artist_name_5" : "Kwon Ye Ji",
        "exhibit_artist_name_6" : "Kim So Jeong",
        "exhibit_artist_name_7" : "Park Gyu Ri",
        "exhibit_artist_name_8" : "Lee Yeo Jin",
        "exhibit_artist_name_9" : "Yang I Saac",
        "exhibit_artist_name_10" : "Choi Su Bin",
        "exhibit_artist_name_11" : "Kang Ji su",
        "exhibit_artist_name_12" : "Lee Hye Jin",
        "exhibit_artist_name_13" : "Lee chae hyeon",
        "exhibit_artist_name_14" : "Won You Kyong",
        "exhibit_artist_name_15" : "Lee So hyung",
        "exhibit_artist_name_16" : "DANA KIM, CHAERIN LEE, YUGYEONG CHUNG",
        "exhibit_artist_name_17" : "NAHYUN KIM, DOHYANG KIM, SINYOUNG HWANG",
        "exhibit_artist_name_18" : "SUJIN KWON, JIYEON KIM, YERIM PARK",
        "exhibit_artist_name_19" : " CHANYOUNG SONG, JIHYE YU, SIEUN CHA",
        "exhibit_artist_name_20" : "JIALI CHEN, YUNJIA CHU, XIN LI ",
        "exhibit_artist_name_21" : "SONGLIM KIM, YUYEON NAM, SUAN EUN, NAYEON CHO",
        
        "exhibit_artist_name_22" : "Youngwoo Kim",
        "exhibit_artist_name_23" : "Nana",
        "exhibit_artist_name_24" : "CheolWon Chang",
        "exhibit_artist_name_25" : "injong Choi  ",


        "art_list_1" : "Swimming",
        "art_list_2" : "Where a day is baked",
        "art_list_3" : "LATENT IMAGE",
        "art_list_4" : "Petals of the Mind",
        "art_list_5" : "A Square Summer in a Square Room",
        "art_list_6" : "summer vacation",
        "art_list_7" : "The Horse",
        "art_list_8" : "Adapting in Our Own Ways",
        "art_list_9" : "BEYOND THE WINDOW",
        "art_list_10" : "Sweet Summer",
        "art_list_11" : "The Moment Nacre Unfolds",
        "art_list_12" : "Make A Wish",
        "art_list_13" : "A Day in June",
        "art_list_14" : "A Fairy Tale",
        "art_list_15" : "Shimmering deep wave",
        "art_list_16" : "CheonMun",
        "art_list_17" : "Seoul Soulmates",
        "art_list_18" : "Threshold",
        "art_list_19" : "Flowing Seoul",
        "art_list_20" : "Wind Across Seoul",
        "art_list_21" : "Intrusion",
        
        "art_list_22" : "The four seasons",
        "art_list_23" : "Hello Again, Rain",
        "art_list_24" : "Today, That Mountain",
        "art_list_25" : "Connection : From Cell to Galaxy",


        "artist_name_1" : "Hwang Se Hee",
        "artist_name_2" : "Jeon Soo Ah",
        "artist_name_3" : "Park Ji Hyeon",
        "artist_name_4" : "Kim Seo Yun",
        "artist_name_5" : "Kwon Ye Ji",
        "artist_name_6" : "Kim So Jeong",
        "artist_name_7" : "Park Gyu Ri",
        "artist_name_8" : "Lee Yeo Jin",
        "artist_name_9" : "Yang I Saac",
        "artist_name_10" : "Choi Su Bin",
        "artist_name_11" : "Kang Ji su",
        "artist_name_12" : "Lee Hye Jin",
        "artist_name_13" : "Lee chae hyeon",
        "artist_name_14" : "Won You Kyong",
        "artist_name_15" : "Lee So hyung",
        "artist_name_16" : "DANA KIM, CHAERIN LEE, YUGYEONG CHUNG",
        "artist_name_17" : "NAHYUN KIM, DOHYANG KIM, SINYOUNG HWANG",
        "artist_name_18" : "SUJIN KWON, JIYEON KIM, YERIM PARK",
        "artist_name_19" : " CHANYOUNG SONG, JIHYE YU, SIEUN CHA",
        "artist_name_20" : "JIALI CHEN, YUNJIA CHU, XIN LI ",
        "artist_name_21" : "SONGLIM KIM, YUYEON NAM, SUAN EUN, NAYEON CHO",
        
        "artist_name_22" : "Youngwoo Kim",
        "artist_name_23" : "Nana",
        "artist_name_24" : "CheolWon Chang",
        "artist_name_25" : "injong Choi  ",


        "art_explain_1" : "〈Swimming〉 captures the vibrant movement of clouds drifting slowly across the sky and cosmos flowers swaying gently in the breeze, viewed from beneath a field of blooming cosmos.\n\nEarly summer in June is the season when life breathes most vividly. Lying in a field of cosmos beneath a clear blue sky, viewers are invited to immerse themselves in the air, light, and gentle flow of the moment, as if swimming through summer itself.\n\nAmid the fast pace of urban life, the work encourages viewers to pause for a moment and rediscover the sky and the changing seasons—details that often go unnoticed in everyday life.\n\nLike drifting gently through a quiet June day, the work offers a tranquil moment of reflection and rest.",
        "art_explain_2" : "In the fast-paced rhythm of life in Seoul, people are constantly on the move, often losing sight of moments of rest. Having felt the same lack of time to pause in my own busy life, I wanted to create a space that offers warmth and comfort through this work.\n\nThis idea inspired the concept of The Mice's Apple Pie Shop, a place where time flows at a different pace from reality. Through the gentle scenes of little mice slowly baking apple pies and enjoying a picnic, the work embraces a sense of calm and coziness. A rolling apple that suddenly startles the mice adds a touch of lively energy to the otherwise peaceful atmosphere.\n\nI hope this work becomes a small pause in the midst of busy everyday life—a moment that allows viewers to slow down, breathe, and rediscover a sense of rest and healing.",
        "art_explain_3" : "The title Latent Image is a photographic term referring to an image that has been recorded on film but has not yet become visible. Inspired by this concept, the work translates the hidden nature of dreams and memories into a pattern-based media artwork.\n\nThroughout the video, floral forms and patterns repeat, expand, and continuously transform. Blurred silhouettes briefly emerge into clarity before fading away, while overlapping images intertwine to create new visual scenes. These ever-changing patterns symbolize fragments of memory and the flow of emotions that surface within dreams.\n\nIn dreams, familiar memories, emotions, and everyday scenes often reappear in unexpected forms. This work visualizes those dreamlike experiences through patterns and movement, capturing fleeting moments when unseen images emerge and disappear.\n\nAs viewers follow the constantly shifting forms and rhythms, they are invited to trace the lingering impressions of dreams and memories, ultimately encountering their own emotions and imagination.",
        "art_explain_4" : "This media artwork visualizes the invisible flow of human emotions through organic floral forms and gentle movement.\n\nIn our daily lives, we experience a wide range of emotions—joy, anxiety, excitement, and serenity. Yet emotions cannot be confined to a single form; they continuously blend, evolve, and transform. This work translates these ever-changing emotional currents into abstract floral imagery and fluid motion.\n\nFlowers bloom and scatter in an endless cycle, symbolizing the emergence, transformation, and renewal of emotion. Their overlapping, interconnected movements reflect the way emotions shift and circulate over time, while the soft interplay of form and texture gives visual shape to feelings that cannot be seen.\n\nAs the floral forms continuously transform, they reveal the process by which complex emotions blossom, dissolve, and merge into a single flowing rhythm. Through this visual language, the work invites viewers to experience the intangible landscape of the inner self.",
        "art_explain_5" : "The sea is one of the first images that comes to mind when we think of summer. Even if busy days make it impossible to visit the coast, a small toy aquarium in one's room can still evoke the feeling of the ocean.\n\nWatching the tiny sea unfold within its small, square frame, time seems to quietly slip away.\n\nIt is as if one were gazing at a square aquarium inside a square room through the square screen of Seoullo Media Canvas.",
        "art_explain_6" : "Summer Vacation is a media artwork that follows a journey in search of complete liberation from the fast-paced and overwhelming rhythm of urban life. As the scene shifts from a cityscape filled with neon lights, an emerald-blue ocean unfolds before the viewer alongside a refreshing cocktail, opening the door to an entirely different world.\n\nLeaving behind late nights at work and the demands of everyday life, the work transports viewers to the kind of peaceful, exotic destination that many dream of escaping to. The landscapes of a seaside resort, unfolding seamlessly from day to night, dissolve the sense of confinement and invite viewers into a dreamlike space, offering a liberating escape from the pressures of daily life.",
        "art_explain_7" : "Created to mark 2026, the Year of the Horse, this work features horses of various forms crossing the screen, each moving at its own pace. The horses symbolize people who continue moving forward in their own way amid the repetitive rhythm of everyday life. Some run swiftly, while others walk slowly. Though they differ in size, form, and speed, each follows its own rhythm.\n\nWe often compare ourselves to others, measuring our lives by their pace and direction. This work instead celebrates the value of living according to one's own rhythm, portraying different beings moving together within the same shared space.\n\nThe horses travel without a fixed destination, mirroring our lives in today's fast-moving society, where we are constantly encouraged to keep moving forward. Although we do not all walk the same path, we continue steadily toward our own destinations in our own ways.\n\nBy bringing together beings of different forms, rhythms, and movements within a single space, the work invites viewers to reflect on their own journey and the unique pace at which they move through life.",
        "art_explain_8" : "The jelly bears living in the city are all born alike, yet each follows a completely different path depending on the environment they encounter. Some melt beneath the intense heat of the sun, some move to avoid danger, while others adapt to new surroundings in their transformed forms.\n\nViewing the city as a microcosm of society, this work explores the diverse ways in which individuals survive and adapt. Although they begin under the same conditions, their lives unfold in remarkably different ways as they respond to the environments around them.",
        "art_explain_9" : "In a small room after nightfall, a boy lost in boredom finds a small paper airplane flying toward him. Without hesitation, he follows it, acting on an impulse strong enough to make him leap toward the window.\n\nAt that moment, the figure beside him quickly grabs hold of him, and the two briefly confront a moment of crisis together.\n\nBased on the universe of *PROJECT : SHOMA*, this work is a 3D anamorphic media façade video that captures the relationship between the two characters, their contrasting personalities revealed through action, and the flow of emotion within a short narrative.\n\nThe video is structured around an emotional progression that begins with boredom and moves through curiosity, immersion, tension, relief, and lingering afterthought. Through a fixed camera and one-take format, the work emphasizes spatial continuity and a sense of immersion. Visual elements such as framed images in the background and the cityscape outside the room also subtly suggest fragments of the work’s larger fictional universe.",
        "art_explain_10" : "Guided by the keywords “summer” and “childhood innocence,” this work refreshes the urban landscape with vivid and whimsical imagination.\n\nIt depicts fantasies that many people once dreamed of in childhood: a giant slide soaring through the air against gravity, touching floating clouds and tasting them like cotton candy, riding a vehicle that drifts across the sky carried by countless balloons, and even licking walls made of ice cream.\n\nThe blue summer sky and the jelly bears floating through it stand in contrast to the composed and restrained behavior expected of us as adults. Through these sweet childhood imaginings, the work offers a sense of liberation and a refreshing moment of rest.",
        "art_explain_11" : "The Moment Mother-of-Pearl Unfolds begins with the idea of Korean traditional mother-of-pearl as a surface that contains an entire world. Although its intricate patterns appear to be fixed decorative motifs on crafted objects, they reveal shifting colors with changes in light and hidden images through their layered textures. Inspired by these unique qualities, the work imagines the moment when the world concealed within the patterns expands into physical space. Through light and movement, mother-of-pearl becomes a living medium that unfolds into a space filled with landscapes, life, and memories.\n\n**The work brings the hidden world within the mother-of-pearl patterns into reality before guiding it back into the surface from which it emerged. What once appeared as a static ornament briefly transforms into a living landscape; the surface expands into an immersive space, only to return once more",
        "art_explain_12" : "As children, we would close our eyes and make wishes with sincere hearts before blowing out the candles on our birthday cakes. Those wishes were often simple or whimsical, yet they reflected our honest dreams and hopes for the future.\n\nAs time passes and we grow into adulthood, however, the weight of reality gradually shifts our focus toward practical and material goals. Along the way, the pure hopes and dreams we once cherished often become buried deep within our memories.\n\nThis work invites viewers to recall the wishes they may have forgotten and to reflect on how closely their present lives resonate with the dreams they once held. By evoking the excitement of that fleeting moment before blowing out the candles—with hands clasped and hearts full of hope—it encourages viewers to rediscover the aspirations and possibilities that still remain within them.\n\nThe artist hopes this work rekindles the forgotten spark of childhood wishes, offering a gentle opportunity to reflect on who we are today with kindness and compassion.",
        "art_explain_13" : "Inspired by the traditional Korean holiday of Dano, this 2D media artwork unfolds the rhythm of a single day in the lives of people from the past. From the stillness of morning to sunset and the arrival of night, it weaves together the many moments of Dano into one continuous landscape.\n\nTraditionally celebrated after the rice planting season, Dano was a time to pause from daily labor and pray for a bountiful harvest, good health, and peace. People washed their hair with sweet flag-infused water, enjoyed swinging, and gathered in nature to celebrate the changing season and the well-being of their communities. Through subtle movements and carefully composed visual elements, the work captures the customs and spirit of Dano, preserving memories of a fading past.\n\nThe slowly unfolding composition is designed not simply to recreate a traditional scene, but to evoke the sensation of time gently passing over the course of a single day. Mist-like backgrounds and recurring movements recall the lingering impressions of landscapes that remain somewhere in our memories, inviting viewers to wander briefly through the quiet passage of the past.",
        "art_explain_14" : "This work brings together two classic narratives—The Wizard of Oz and the Korean folktale The Tale of Sim Cheong—to depict the moment when Sim Cheong, after falling into the sea, awakens in an unfamiliar world.\n\nAs she journeys through vast mountains and encounters schools of fish, Sim Cheong moves through a dreamlike realm where reality and fantasy intertwine. As the narrative unfolds, the colors gradually shift, revealing another world imbued with both Eastern aesthetics and fantastical imagery.\n\nRather than portraying a fall as a purely negative experience, the work reimagines it as a passage toward unexpected encounters. Just as new landscapes and light emerge in the act of falling, moments of uncertainty and vulnerability can also become meaningful and beautiful parts of life's journey.",
        "art_explain_15" : "Within the screen before us unfolds a pure and luminous ocean, shaped by the interplay of light and color. Soft waves, washed in dreamy pastel hues, reveal nature's most delicate palette, while shimmering white rays of light illuminate fleeting moments with quiet brilliance. Filling this tranquil seascape are schools of fish, alive with graceful movement. Swimming together in vibrant colors, they resemble a grand choreography performed by nature itself.\n\nAs viewers set aside the noise of everyday thoughts and follow the gently rippling waves, they are invited to immerse themselves in the sensory beauty of nature and the vibrant energy of life. In doing so, the work offers a quiet yet profound sense of freedom and renewal.",
        "art_explain_16" : "The Korean word Cheonmun refers both to the natural phenomena of the sky and to the study of the heavens.\n\nInspired by the spirit of astronomical observation, this work reimagines the sky above Seoul through a new perspective, portraying a nocturnal landscape where the city and media seamlessly converge. Like ink slowly spreading across paper, washes of black ink bloom through the night sky, while scattered stars become points and lines that connect to one another. Gradually, the night sky of Seoul unfolds as a vast ink painting, its constellations woven together into a single flowing composition.",
        "art_explain_17" : "The Diversity of Seoul, Stronger Together\n\nIn the fast-paced rhythm of Seoul, people often become absorbed in their own lives. Although they share the same city, many remain disconnected from one another, living as isolated individuals. Yet Seoul is a city where people of diverse backgrounds, personalities, and values live side by side, and it is through these differences that the city finds its greatest strength.\n\nHaechi and the Haechi Friends embody this spirit of Seoul. As once-separated characters come together and build meaningful connections, they celebrate the city's vibrant diversity and the value of coexistence. Through their bright and approachable personalities, the work conveys the message that a stronger community is created when people with different backgrounds come together.",
        "art_explain_18" : "Tradition is not something that remains in the past, but a passage that moves through the present toward the future.\n\nThreshold reinterprets the beauty and values of traditional Korean elements through a contemporary lens, transforming them into a visual rhythm that reflects the city of Seoul.\n\nIts recurring patterns embody both the cadence of everyday life and the movement of the city, inviting viewers to pause amid the complexity of modern life and rediscover their surroundings. Through this experience, the work reveals the quiet palette and restrained elegance inherent in Korean tradition.\n\nThese elements no longer function as Threshold, but as passages—bridging tradition and modernity, the interior and the exterior, while inviting viewers to move freely between them.",
        "art_explain_19" : "Every day, we pass through Seoul. Beyond the windows of moving trains, countless faces of the city quietly unfold.\n\nThis work follows Seoul's landmarks and urban landscapes as seen through the window of a subway train, capturing the rhythm of a single day. It invites viewers to slow down and appreciate the familiar beauty of the city—scenery that often slips past unnoticed in the rush of everyday life.",
        "art_explain_20" : "Inspired by the theme of wind, this multimedia artwork presents Seoul through a variety of perspectives. Guided by the movement of the wind, the viewer journeys past iconic landmarks such as Seoul Station, N Seoul Tower, and Gyeongbokgung Palace. The wind takes the form of drifting flower petals, and wherever they pass, the urban landscape transforms into scenes reminiscent of traditional Korean painting.\n\nThe work draws inspiration from Irwol Obongdo (The Sun, Moon, and Five Peaks), reinterpreting its symbolic imagery—the sun and moon, mountains and rivers, and the natural world—through a contemporary visual language. As a result, familiar views of Seoul are transformed into poetic landscapes where the city, nature, tradition, and modernity coexist in harmony.\n\nFor first-time visitors, the work also serves as a visual guide to the city, introducing Seoul's major cultural and historical landmarks through an immersive artistic journey.",
        "art_explain_21" : "Intrusion marks the moment when the subject of a space begins to shift.\n\nHumans occupy nature and construct buildings upon it. Yet nature does not disappear—it remains, reclaiming the space in different ways.\n\nThrough traces of nature emerging within human-made structures, this project questions who truly belongs to a place and who ultimately becomes its subject.\n\nIntrusion is never a one-way act. Humans encroach upon nature, and nature, in turn, re-enters human space.\n\nThe cycle of intrusion continues.",
        
        "art_explain_22" : "Inspired by the symbolic imagery of Korean minhwa (folk paintings), this work reinterprets traditional motifs through a contemporary lens, unfolding as a visual journey through the four seasons.\n\nThe video begins with Hwajodo (Paintings of Flowers and Birds), where blooming flowers and birds announce the arrival of spring. As rain falls, hydrangeas blossom and butterflies flutter among them, evoking Chochungdo (Paintings of Flowers and Insects) and capturing the delicate transition from spring to summer. As the hydrangeas fade, lotus leaves and blossoms emerge, joined by dragonflies whose appearance subtly signals the approach of autumn while offering another interpretation of Chochungdo.\n\nRipened rice fields, crickets, and drifting autumn leaves soon reveal the fullness of the season. Two cranes then appear, guiding the viewer toward layered mountain ranges. Together, the cranes and mountains evoke Jangsaengdo (Paintings of the Ten Symbols of Longevity), before snow begins to fall and an endless winter landscape unfolds.\n\nJust as the symbolic elements of minhwa are woven into the cycle of the four seasons, the work expresses a wish for peace, harmony, and enduring hope throughout the passage of time.",
        "art_explain_23" : "Hello Again, Rain is an illustrated media artwork that portrays the revival of a forest after rainfall returns to land long parched by drought. Through painterly imagery and expressive brushstrokes, the work gently reveals the forest's transformation.\n\nBeginning with cracked earth and a silent woodland, life slowly awakens as the first raindrops begin to fall. Rain becomes a source of renewal, restoring the forest while revealing the interconnectedness of all living things. Through nature's quiet recovery, the work invites viewers to rediscover a sense of connection with the natural world that may have been forgotten.",
        "art_explain_24" : "For nearly three years, I photographed the same mountain and sky from the same place almost every morning. There was no particular intention or destination at the beginning—I simply found myself drawn to the familiar landscape I encountered each day.\n\nAlthough the photographs were taken from the same viewpoint, the scenery was never the same. Changes in weather, seasons, light, and the density of the air continually transformed the mountain and the sky. These subtle variations were difficult to perceive in a single image, yet over time they accumulated into a continuous flow.\n\nThis video is composed by connecting those photographs through gentle fade transitions, visualizing the passage of time that quietly settles within a familiar landscape and revealing the gradual transformations that often go unnoticed.",
        "art_explain_25" : "This work explores the organic relationship and eternal cycle connecting microscopic cells and the vast universe through the primordial vitality of nature emerging within the rigid gray landscape of human civilization. Breaking through cold artificial grids, vibrant forms rise and evolve into a surreal ecosystem inspired by nature's own order. Blossoming flowers, growing stems, and shimmering spheres embody the dynamic energy of life as they bloom, wither, and flourish in an endless cycle.\n\nFrom these microscopic beginnings, the energy of life expands into the immense scale of nebulae and galaxies, suggesting that every living existence in nature is intricately connected without separation.\n\nAccompanied by tranquil ambient sound, this visual journey follows the path of existence—from the smallest cell to its return within the infinite cycle of the cosmos. In doing so, the work invites viewers to imagine the organic relationships between the colors, forms, and visual poetry of nature that extend far beyond the screen.",

        // "time_table_title" : "Information",
        // "time_table_title_1" : "Art",
        // "time_table_title_2" : "DongHaeng\n(empathy)",
        // "time_table_title_3" : "MaeRyeok\n(charming)",
        // "time_table_title_sub_1" : "The Origin of All Beginnings",
        // "time_table_title_sub_2" : "Moment Seoul",
        // "time_table_title_sub_3" : "Hangang Nature",
        // "time_table_art_1" : "1. Lee Donah 〈Odyssey to Infinite Happiness〉",
        // "time_table_art_2" : "2. Choi Sungrok 〈Seoul Sky of Transforming Clouds〉",
        // "time_table_art_3" : "",
        // "time_table_art_4" : "3. Spring Message of Support from Seoul",
        // "time_table_art_5" : "4. Haechi's Seoul Journey",
        // "time_table_art_6" : "5. Little Maengkkongi's Adventure",
        // "time_table_art_7" : "6. Lee Donah 〈Hwajodo in Space〉",
        // "time_table_art_8" : "7. Choi Sungrok 〈Genesis Canyon〉",
        // "time_table_art_9" : "",
        // "time_table_art_10" : "8. Spring Message of Support from Seoul",
        // "time_table_art_11" : "9. Haechi's Seoul Journey",
        // "time_table_art_12" : "10. Little Maengkkongi's Adventure",

        // "directions_title" : "Location",

        // "directions_explain_title_1" : "Subway",
        // "directions_explain_title_2" : "Bus",
        // "directions_explain_title_3" : "Green Bus (Local Route)",

        // "directions_explain_1" : "Line 1\nYongsan Station - Exit 5 → Walk about 300m to Yongsan Station\nBus Stop (03-004) → Take a bus toward Nodeul Island → Get off at\nNodeul Island Stop (03-340) → Enter via the access road next to the East Parking Gate\n\nLine 4\nSinyongsan Station – Exit 3 → Walk 100m to Sinyongsan Station\nBus Stop (03-004) → Take a bus toward Yongsan / Nodeul Island →\nContinue toward Hangang Bridge for about 700m → Get off at Nodeul Island Stop (03-340) → Enter via the access road next to the East Parking Gate\n\nLine 9\nNodeul Station - Exit 2 → Walk approximately 700m toward\nHangang Bridge → Enter via the access road next to the East Parking Gate\n",
        // "directions_explain_2" : "Blue Bus (Main Routes)\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752",
        // "directions_explain_3" : "6211\n→ Get off and enter via the access road next to the East Parking Gate\n\nHangang Bus\nThe exhibition is visible while riding between Yeouido and Apgujeong.",
    },
    ja : {
        "index_button_introduce" : "(일본어)아뜰리에 노들 소개",
        "index_button_schedule" : "(일본어)상영 시간표",
        "index_button_exhibit" : "(일본어)예술 미디어스케이프",
        "index_button_exhibit_sub" : " ",
        "index_button_art_1" : "(일본어)동행 모먼트서울",
        "index_button_art_1_sub" : " ",
        "index_button_art_2" : "(일본어)매력 한강네이처",
        "index_button_art_2_sub" : " ",
        
        "back_button_text" : "BACK",
        "top_button_text" : "(일본어)Top",
        "list_button_text" : "list",
        "prev_button_text" : "(일본어)이전",
        "next_button_text" : "(일본어)다음",

        "schedule_explain_name" : "(일)아뜰리에노들 미디어아트 상영 시간표",
        "atelier_nodeul_name" : "(일본어)아뜰리에 노들",
        "atelier_nodeul_explain" : "(일본어)아뜰리에 노들 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "schedule_name" : "(일)작품명",
        "schedule_time" : "(일)상영 시간",

        "exhibit_title" : "(일본어)전시 소개",        
        "exhibit_introduce" : "(일본어)전시 소개\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        "exhibit_explain" : "(일본어)전시 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "link_button_text" : "(일본어)영상 보러가기",

        "exhibit_name_1" : "(일)예술: 미디어스케이프 (Mediascape)",
        "artist_name_1" : "(일본어)작가명1",
        "art_name_1" : "(일본어)작품명1",
        "art_explain_1" : "(일본어)작품 설명1\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_2" : "(일본어)전시명2",
        "artist_name_2" : "(일본어)작가명2",
        "art_name_2" : "(일본어)작품명2",
        "art_explain_2" : "(일본어)작품 설명2\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_3" : "(일본어)전시명3",
        "artist_name_3" : "(일본어)작가명3",
        "art_name_3" : "(일본어)작품명3",
        "art_explain_3" : "(일본어)작품 설명3\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",

        "directions_explain" : "(일)지하철\n1호선\n용산역 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004) 노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번 출구 - 도보 100m 위치 신용산역 정류장(03-004) 용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n\n버스\n간선 버스\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\n자선 버스\n6211"
    }
    
}
