const translations = {
    ko: {
        "index_button_introduce" : "서울로미디어캔버스 소개",
        "index_button_schedule" : "상영 시간표",
        "index_button_exhibit" : "전시 소개",
        "index_button_exhibit_sub" : "",
        "index_button_art_1" : "신진예술가 지원전시",
        "index_button_art_1_sub" : "",
        "index_button_art_2" : "네이처 프로젝트전",
        "index_button_art_2_sub" : "",
        "index_button_directions" : "오시는 길",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        // "atelier_nodeul_name" : "아뜰리에 노들",
        // "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        // "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        // "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<아뜰리에 노들 2026 첫 번째 전시 : 시작의 근원> 전시 시간표",
        "schedule_explain_date" : "전시 기간: 2026.05.22.(금) ~ 2026.07.31.(금)",
        "schedule_explain_pos" : "상영 장소: 노들섬 남단 한강대교 교각 하부 미디어파사드",
        "schedule_explain_pos_detail" : "노들섬 아트라운지 미디어볼 상명 시간",
        "schedule_explain_time" : "상영 시간: 20:00 ~ 22:00 (매 시각 정시 상영)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        // "exhibit_intro_title" : "전시 소개",        
        // "exhibit_introduce_name" : "2026 아뜰리에 노들 첫 전시 : 시작의 근원\nAtelier Nodeul 2026 1st Exhibition : The Origin of All Beginnings",
        "exhibit_introduce" : "서울로미디어캔버스는 시민이 향유하고 공감할 수 있는\n미디어아트와 영상 콘텐츠 등 전자적 빛으로 이루어진\n예술작품을 지속 전시하여 미디어아트의 영역을 확장하는\n미디어아트 전문 플랫폼입니다.",
        // "exhibit_introduce_sub" : "*특정 지역이나 환경을 대표하면서 사람들의 관심과 보호의식을 이끌어내기 위해 선정된 상징적인 생물종",
        // "exhibit_explain_name_1" : "시작의 근원",
        // "exhibit_explain_1" : "'시작의 근원 The Origin of All Beginnings'은 한강 노들섬에서 펼쳐지는 미디어아트 전시로, 도시의 빛과 물결이 교차하는 지점에서 기원과 생성의 순간을 탐구합니다.\n이돈아, 최성록 두 미디어아티스트의 다채롭고 역동적인 작품을 통해 노들섬의 예술적 매력과 한강의 새로운 가능성을 재조명합니다.",
        // "exhibit_explain_name_2" : "모먼트 서울",
        // "exhibit_explain_2" : "서울의 핵심 가치인 ‘약자와 동행하는 상생 도시’를 강조합니다.\n〈서울응원 메시지〉를 통해 새로운 시작을 앞둔 시민들에게 응원의 메시지를 전달하고, 〈해치와 서울나들이〉는 노들섬과 한강변을 배경으로, 노들섬에서 출발해 서울 상공으로 이어지는 여정을 그립니다.",
        // "exhibit_explain_name_3" : "한강 네이처",
        // "exhibit_explain_3" : "한강 네이처는 서울의 비전인 ‘매력’을 상징하며, 자연이 살아 숨 쉬는 한강 노들섬의 생태를 미디어아트로 풀어낸 자연도감입니다.\n맹꽁이를 주인공으로 한 옴니버스 애니메이션으로, 새로운 터전을 찾아가는 여정을 통해 노들섬의 생태와 계절의 변화, 그리고 서울과 한강의 다양한 모습을 전합니다.",
        
        "exhibit_2_intro_title" : "전시 소개",        
        "exhibit_2_introduce_name" : "세 번째 전시 09.21.-11.30.",
        "exhibit_2_introduce" : "서울로미디어캔버스의 2026년 세 번째 전시는 계절이 변화하는 도심 속에서 자연을 바라보는 새로운 시선과 신진예술가들의 다채로운 창작 세계를 소개합니다. 이번 전시는 신진예술가 지원전시와 네이처 프로젝트전으로 구성되며, 공모를 통해 발굴한 창작자들의 새로운 시도와 자연을 각기 다른 관점으로 해석한 미디어아트를 선보입니다.",
        // "exhibit_2_introduce_sub" : "*특정 지역이나 환경을 대표하면서 사람들의 관심과 보호의식을 이끌어내기 위해 선정된 상징적인 생물종",
        "exhibit_2_explain_name_1" : "신진예술가 지원전시",
        "exhibit_2_explain_1" : "신진예술가 지원전시는 공모를 통해 선정된 신진예술가들의 작품을 소개하며, 창작자들의 자유로운 상상력과 실험적인 표현을 조명합니다. 개인의 기억과 감정, 일상의 풍경과 관계, 전통과 현대 등 다양한 주제를 자신만의 시각 언어로 풀어낸 작품들을 통해 새로운 미디어아트의 가능성을 만나볼 수 있습니다.",
        "exhibit_2_explain_name_2" : "네이처 프로젝트전",
        "exhibit_2_explain_2" : "네이처 프로젝트전은 자연과 인간의 관계를 비롯해 자연이 지닌 생명력과 순환의 가치를 다양한 시선으로 바라봅니다. 사계절의 풍경과 자연의 관계, 전통적 소재와 자연의 조화, 도시와 자연이 주고받는 감각과 흔적을 담아낸 작품들은 자연을 새롭게 바라보는 경험과 사유의 시간을 선사합니다.",
        // "exhibit_2_explain_name_3" : "한강 네이처",
        // "exhibit_2_explain_3" : "한강 네이처는 서울의 비전인 ‘매력’을 상징하며, 자연이 살아 숨 쉬는 한강 노들섬의 생태를 미디어아트로 풀어낸 자연도감입니다.\n맹꽁이를 주인공으로 한 옴니버스 애니메이션으로, 새로운 터전을 찾아가는 여정을 통해 노들섬의 생태와 계절의 변화, 그리고 서울과 한강의 다양한 모습을 전합니다.",
        
        "link_button_text" : "영상 보러가기",

        "exhibit_3_introduce" : "신진예술가 지원전시는 「2026 서울로미디어캔버스 신진예술가 지원전시」 공모를 통해 선정된 평면 및 영상 분야 신진예술가들의 작품으로 구성되었습니다.\n\n신진예술가 지원전시는 새로운 시각과 감각을 지닌 창작자들의 다양한 작품 세계와 예술적 가능성을 조명합니다. 개인의 기억과 감정, 일상의 풍경과 관계, 자연과 도시, 전통과 현대 등 다양한 주제를 자신만의 시각 언어와 표현 방식으로 풀어낸 작품들은 익숙한 일상을 새롭게 바라보는 시선을 제시하며, 미디어아트의 다채로운 가능성을 보여줍니다.",
        "exhibit_4_introduce" : "네이처 프로젝트전은 「2026 서울로미디어캔버스 네이처 프로젝트전」 2차 공모에서 선정된 작품들로 구성되었습니다.\n\n네이처 프로젝트전은 자연과 인간, 도시가 맺고 있는 다양한 관계를 새로운 시선으로 바라봅니다. 사계절의 풍경과 자연의 순환, 전통적 소재와 자연의 조화, 도시의 일상 속에서 마주하는 자연의 감각과 흔적을 담아낸 작품들은 자연과 우리의 관계를 새롭게 바라보는 다양한 관점을 제시하며 관람객들에게 사유의 시간을 선사합니다.",

        "exhibit_name_1" : "신진예술가 지원전시",
        "exhibit_name_2" : "네이처 프로젝트전",

        "exhibit_list_1" : "걷다",
        "exhibit_list_2" : "다섯 가지 이야기",
        "exhibit_list_3" : "기억의 빛, 세상을 짓다.",
        "exhibit_list_4" : "달토끼의 여정",
        "exhibit_list_5" : "여정의 시작",
        "exhibit_list_6" : "모두의 긴 식탁 — 한 자리 더 있어요 ",
        "exhibit_list_7" : "일상의 연속",
        "exhibit_list_8" : "시간은 흐른다.",
        "exhibit_list_9" : "돌로 지은 글자",
        "exhibit_list_10" : "그 곳",
        "exhibit_list_11" : "그리운 이팝나무",
        "exhibit_list_12" : "신록의 피어남",
        "exhibit_list_13" : "별나라의 모험",
        "exhibit_list_14" : "단청비",
        "exhibit_list_15" : "이상한 오후",
        "exhibit_list_16" : "희망의 땅, DMZ",
        "exhibit_list_17" : "디지털캔버스: 파사드의 진화",
        "exhibit_list_18" : "같은 배",
        "exhibit_list_19" : "하나, 들. 셋!",
        "exhibit_list_20" : "고담 (古談)",
        
        "exhibit_list_21" : "서원의 사계",        
        "exhibit_list_22" : "자개몽유도",
        "exhibit_list_23" : "자연의 관계",
        "exhibit_list_24" : "열의 기억을 대하는 방법",
        "exhibit_list_25" : "",


        "exhibit_artist_name_1" : "김재민",
        "exhibit_artist_name_2" : "김아롬새미",
        "exhibit_artist_name_3" : "김정민",
        "exhibit_artist_name_4" : "김지인",
        "exhibit_artist_name_5" : "송도영",
        "exhibit_artist_name_6" : "신혜원",
        "exhibit_artist_name_7" : "안수아",
        "exhibit_artist_name_8" : "엘리",
        "exhibit_artist_name_9" : "이종훈",
        "exhibit_artist_name_10" : "정미정",
        "exhibit_artist_name_11" : "김보미, 오수아",
        "exhibit_artist_name_12" : "김유미",
        "exhibit_artist_name_13" : "김재원",
        "exhibit_artist_name_14" : "노우영",
        "exhibit_artist_name_15" : "박정화",
        "exhibit_artist_name_16" : "신종인",
        "exhibit_artist_name_17" : "이여운",
        "exhibit_artist_name_18" : "이채영",
        "exhibit_artist_name_19" : "장현지",
        "exhibit_artist_name_20" : "허건",

        "exhibit_artist_name_21" : "김도영",        
        "exhibit_artist_name_22" : "김리아",
        "exhibit_artist_name_23" : "전승일",
        "exhibit_artist_name_24" : "최민규",

        "exhibit_artist_name_25" : "",

        "art_list_1" : "<걷다>",
        "art_list_2" : "<다섯 가지 이야기>",
        "art_list_3" : "<기억의 빛, 세상을 짓다.>",
        "art_list_4" : "<달토끼의 여정>",
        "art_list_5" : "<여정의 시작>",
        "art_list_6" : "<모두의 긴 식탁 — 한 자리 더 있어요 >",
        "art_list_7" : "<일상의 연속>",
        "art_list_8" : "<시간은 흐른다.>",
        "art_list_9" : "<돌로 지은 글자>",
        "art_list_10" : "<그 곳>",
        "art_list_11" : "<그리운 이팝나무>",
        "art_list_12" : "<신록의 피어남>",
        "art_list_13" : "<별나라의 모험>",
        "art_list_14" : "<단청비>",
        "art_list_15" : "<이상한 오후>",
        "art_list_16" : "<희망의 땅, DMZ>",
        "art_list_17" : "<디지털캔버스: 파사드의 진화>",
        "art_list_18" : "<같은 배>",
        "art_list_19" : "<하나, 들. 셋!>",
        "art_list_20" : "<고담 (古談)>",

        "art_list_21" : "<서원의 사계>",        
        "art_list_22" : "<자개몽유도>",
        "art_list_23" : "<자연의 관계>",
        "art_list_24" : "<열의 기억을 대하는 방법>",
        "art_list_25" : "<>",


        "artist_name_1" : "김재민",
        "artist_name_2" : "김아롬새미",
        "artist_name_3" : "김정민",
        "artist_name_4" : "김지인",
        "artist_name_5" : "송도영",
        "artist_name_6" : "신혜원",
        "artist_name_7" : "안수아",
        "artist_name_8" : "엘리",
        "artist_name_9" : "이종훈",
        "artist_name_10" : "정미정",
        "artist_name_11" : "김보미, 오수아",
        "artist_name_12" : "김유미",
        "artist_name_13" : "김재원",
        "artist_name_14" : "노우영",
        "artist_name_15" : "박정화",
        "artist_name_16" : "신종인",
        "artist_name_17" : "이여운",
        "artist_name_18" : "이채영",
        "artist_name_19" : "장현지",
        "artist_name_20" : "허건",

        "artist_name_21" : "김도영",
        "artist_name_22" : "김리아",
        "artist_name_23" : "전승일",
        "artist_name_24" : "최민규",
        "artist_name_25" : "",
        
        "art_explain_1" : "작품 속의 나는 오늘도 어부의 모습으로 하루를 시작한다.\n오늘도 바다로 나가 물고기를 잡고, 내일도 모레도 같은 하루를 살아갈 것이다.\n목적 없이 반복되는 일상 속에서 우리는 과연 자신의 자아를 잃지 않고 살아가고 있을까.\n물고기의 머리를 한 내가 물고기를 잡는 모습은, 반복되는 삶 속에서 결국 자신과 닮은 존재를 붙잡으며 살아가는 우리의 모습을 담고 있다.\n내가 잡아 올리는 물고기는 어쩌면 방향도 목적도 모른 채 바다를 헤엄치는 우리 자신의 모습일지도 모른다.",
        "art_explain_2" : "작가는 내면의 세계 '아로안'을 그린다.\n동생의 죽음으로 인해 내면이 무너지는 경험을 한 이후 저의 내면의 모습을 이미지로 재해석하여 펜으로 기록한다.\n다섯 가지 이야기는 다섯 가지의 그림이 연결된 그림이다.\n각각의 프레임이 전혀 다른 그림이지만 서로 조금씩 연결되는 그림으로 시간의 흐름에 대한 이야기를 담고 있다.\n시간의 흐름에 따라 새로운 사람을 만나거나 새로운 상황을 만나면서 일어나는 사건들을 기록한 그림이다.",
        "art_explain_3" : "서울, 포항, 남해, 라오스(봉사) 등 소중한 기억 속 장소들을 무지갯빛 한지로 붙여 만든 특별한 ‘기억 행성’이다.\n한지에 물감을 색칠하여 스며드는 것을 활용해 자개처럼 반짝이는 빛을 담았다.\n사람마다 마음의 색이 다르고 아름답듯, 긍정적인 기억의 조각을 모아 각자의 마음속에 품는 아름다운 세상, 따뜻한 풍경을 전하고자 한다.",
        "art_explain_4" : "<달토끼의 여정>은 사람들의 소원으로 별을 만드는 달토끼의 이야기다.\n달에서 혼자 살던 달토끼는 새로운 세상과 친구들을 만나기 위해 지구로 여행을 떠난다.\n지구에 가까워질수록 알록달록한 색은 서서히 사라지고, 흑백 두들링 세상이 펼쳐진다.\n달토끼는 낯선 세상을 여행하며 서로를 발견하고 함께하는 즐거움을 알아간다.\n달에서 시작된 작은 소원은 별이 되고, 달토끼의 여행은 지구에서 또 하나의 새로운 이야기가 된다.",
        "art_explain_5" : "병 위에 엎드린 호랑이는 광야와 설원, 어두운 숲과 거대한 공포의 공간을 지나간다.\n호랑이의 모습은 크게 변하지 않지만, 그가 마주하는 세계와 주변의 존재들은 끊임없이 달라진다.\n작품은 실패와 두려움 속에서도 다시 세계를 바라보고 관계 맺으며 살아갈 가능성을 동물들의 우화로 이야기한다.",
        "art_explain_6" : "서로 다른 하루를 보낸 동물 친구들이 음식과 이야기를 들고 긴 식탁에 모인다.\n햇살과 빗방울, 별빛처럼 서로 다른 시간이 한 끼 안에서 자연스럽게 이어지고 친구들은 빵을 건네며 자리를 나눈다.\n식탁 끝에 남겨 둔 빈 의자는 화면을 바라보는 시민에게 보내는 초대이다.\n누구나 환영받고 함께할 때 서울은 더 따뜻하고 풍성한 도시가 된다는 마음을 담았다.",
        "art_explain_7" : "일상에서 스쳐 지나가는 사람과 새, 식물의 움직임을 영상으로 기록하고, 캡처한 장면을 회화로 재구성한다.\n화면 속 존재들은 담기기 전에도 걷고 있었고, 틀에서 벗어난 뒤에도 흘러갈 것들이다.\n움직임의 잔상을 겹쳐 그리며 캔버스 안에서도 끊기지 않는 일상의 연속성을 담는다.\n평범한 일상을 살아내는 일, 그 자체의 가치를 전한다.",
        "art_explain_8" : "한 공간이 선사시대, 조선시대, 현대로 변화하는 모습을 담았다.\n우리 민족을 상징하는 호랑이의 안내를 따라 변함없는 자연과 발전하는 문명의 아름다운 대비를 감상하길 바란다.\n강 위의 거북선과 유람선, 하늘을 나는 익룡과 비행기 등 시공간을 초월한 재미가 곳곳에 숨어 있다.\n과거와 현재가 공존하는 시간 여행을 떠나보길 바란다.",
        "art_explain_9" : "<돌로 지은 글자>는 모양이 서로 다른 돌을 하나씩 살펴 한글의 자음과 모음처럼 보이도록 배치한 작품이다.\n작은 돌들이 모여 글자가 되고, 글자들이 이어져 하나의 문장을 만든다.\n자연이 만든 돌의 모양과 우리가 매일 사용하는 한글이 만나 새로운 모습으로 바뀌는 과정을 통해, 익숙한 글자를 조금 다르게 바라보는 즐거움을 전하고자 했다.",
        "art_explain_10" : "과거의 경험은 시간의 흐름으로 실제와 다를 수도 같을 수도 있게 기억하고 그에 따라 이미지를 시각적으로 형성한다.\n소재는 건물, 빛, 지나치는 사람, 등으로 얽혔다가도 해체하면서 구성하여 드러내는 전체적 이미지는 친숙함과 낯섦을 동시에 보인다. 작품의 시간성을 기반한 '기억'은 친숙하지만 낯선 느낌으로 시각적 이미지를 구성한다.",
        "art_explain_11" : "식목일을 바탕으로, 주인공의 ‘단발머리’를 통해 잘려 나간 나무를 은유적으로 표현했다.\n온전한 과거의 자신을 그리워하던 주인공은 새 이팝나무를 심으며, 이 나무만큼은 꺾임 없이 올곧게 자라기를 간절히 바란다.\n상실의 아픔을 넘어 새 생명에 희망을 담아내며, 자연의 순환과 미래를 향한 치유의 메시지를 전한다.",
        "art_explain_12" : "백제금동대향로 속에 작은 자연의 세계가 숨어 있다고 상상하며 시작한 작품이다.\n향로 속 산과 동물, 그중 사슴에서 영감을 받아 자개빛 사슴과 형광빛의 미래 정원으로 새롭게 표현했다.\n마지막에 전통 창호가 열리며 백제금동대향로가 나타나고, 지금까지 보았던 빛의 세계가 향로에서 시작된 상상이었음을 보여준다.\n오래된 문화유산이 오늘의 빛과 기술을 만나 다시 피어난다는 의미를 담았다.",
        "art_explain_13" : "<별나라의 모험>은 낮과 밤, 땅과 바다가 하나로 이어지는 신기한 세상이다.\n사자, 얼룩말, 헤엄치는 고래, 하늘을 나는 새처럼 생김새도, 살던 곳도 다른 동물들이 한곳 에 모여 평화롭게 움직인다.\n혼자가 아니라 다 함께 어울려 나아가는 동물들의 모습을 보면  마음이  따뜻해진다.\n우리는  서로  달라도  함께  어울려  살아갈  때  가장  행복하다는  메시지를  담은 작품이다.",
        "art_explain_14" : "<단청비>는 한국 전통 단청의 색과 문양에서 출발한 공공 미디어아트 작품이다.\n처마 끝에서 떨어지는 빗방울의 움직임에서 느낀 감각을 바탕으로, 단청의 색채와 문양을 빗방울의 흐름과 결합해 새로운 움직임으로 재구성한다.\n색과 문양의 조각들은 비처럼 흩어지고 낙하하며 반복적인 리듬을 만든다.\n이를 통해 전통을 고정된 이미지가 아닌 시간과 움직임 속에서 새롭게 경험되는 감각으로 확장한다.",
        "art_explain_15" : "거대한 옥수수와 조금 이상한 버섯 생물들. 옥수수 잎은 하늘을 나는 작은 배가 되고, 버섯 위에서 태어난 작은 여행자들은 구름 위 세계로 떠오른다.\n평범한 자연 속에 숨은 또 하나의 세계를 상상하며, 알파카일 수도 버섯일 수도 있는 생명체들처럼 현실과 상상의 경계를 자유롭게 넘나드는 어느 이상한 오후를 그린다.",
        "art_explain_16" : "1945년 38도선에서 시작된 분단의 80년은 전쟁과 철조망을 지나 다시 숲과 생명의 시간으로 이어진다.\n인간이 세운 철조망 위로 수천 마리의 반딧불이가 경계를 지우며 빛의 길을 만든다.\n폐허를 뒤덮고 다시 자라난 생명을 통해 단절을 넘어선 치유와 연결의 희망을 시적으로 그린다.",
        "art_explain_17" : "20여 년간 오래된 건축물의 모습을 수묵화로 그려온 작업들을 디지털 이미지로 변환해 움직이는 영상으로 재구성한 작품이다.\n서울역, 한국은행, 경성우편국 등 서울의 근대 건축물과 한옥, 유럽의 고딕 성당을 하나의 화면에 겹쳐 보여주며 시간과 공간을 넘나드는 새로운 도시 풍경을 만든다.\n전통 수묵과 디지털 미디어를 결합해 과거의 건축과 오늘의 도시를 새롭게 바라보게 한다.",
        "art_explain_18" : "안개 낀 밤바다에 배 한 척이 떠 있다. 배를 지키는 다섯 여자는 모두 똑같은 얼굴이다.\n다섯은 같은 시간에 깨는 법이 없지만, 서로가 남긴 물과 밧줄로 서로를 돌본다.\n어느 밤 물 밑에서 알 수 없는 신호가 올라오고, 처음으로 함께 깨어난 다섯은 하나의 밧줄을 함께 당긴다.\n혼자서는 꿈쩍도 않던 줄이 그제야 끌려온다.\n우리 안의 여러 '나'가 서로를 돌보는 이야기다.",
        "art_explain_19" : "<One, Two, Three!>는 귀여운 아기 토끼 세 마리의 작은 모험을 그린 3D 애니메이션이다.\n당근을 훔치러 밭에 간 토끼들은 정체를 알 수 없는 거대한 그림자를 만나 도망치지만, 사라진 친구를 구하기 위해 다시 용기를 내어 밭으로 향한다.\n밝고 귀여운 캐릭터와 유쾌한 장면, 예상치 못한 반전을 통해 보는 즐거움을 더하고, 친구와 함께라면 무서운 순간도 이겨낼 수 있다는 우정과 용기, 성장의 메시지를 따뜻하게 담아냈다.",
        "art_explain_20" : "“고담, Old Stories”는 말 그대로 오래된 옛이야기를 뜻한다.\n민화 속에는 많은 이야기가 담겨있다. 예로부터 선조들은 민화 속 까치를 통해 새해에 좋은 소식을 물어다 주기를 염원했으며,\n여기에 호랑이를 함께 그려 넣음으로써 나쁜 기운을 쫓아주기를 소망했다고 한다.\n화면을 가득 채운 모란꽃은 풍성하고 화려하게 꽃잎을 피워내는 그 모습에서 재물과 행복의 상징이 되었다고 전해진다.\n이번 작품을 통해 미인도 속 여인이 마치 이야기보따리를 풀어내듯 민화 속 이야기로 우리를 데리고 가는 모습을 상상했다.",
        
        "art_explain_21" : "전통 채색화로 제작한 한국 서원의 사계절 풍경을 모션그래픽으로 확장한 작품이다. 도산서원의 매화, 남계서원의 배롱나무, 도동서원의 은행나무, 소수서원의 소나무를 통해 자연과 한옥이 어우러지는 한국적 미감과 정중동의 미학을 표현한다. 한옥 형태의 한글 타이포그래피와 시적 언어를 결합해 계절의 감정과 풍경을 천천히 사유하는 경험을 제안한다.",
        "art_explain_22" : "자연에서 채취한 자개와 흙으로 빚어진 달항아리에서 시작해, 민화 속 상징 요소를 현대적 미디어아트로 재해석한 작품이다. 자개빛 폭포와 파도, 물고기, 사슴, 학, 백호가 이어지는 몽환적인 풍경을 통해 생명의 증식과 자연의 순환, 평화로운 이상향을 표현한다. 자개의 반사와 유기적인 색의 흐름은 현실과 꿈의 경계를 넘나드는 감각적 경험을 선사한다.",
        "art_explain_23" : "자연의 아름다움과 따뜻함, 그리고 인간과 자연 사이의 관계성을 탐구한 미디어아트 작품이다. 자연은 단순한 풍경이 아니라 인간과 오랜 시간 깊은 관계를 맺어온 삶의 터전이라는 관점에서 출발한다. 영상 속 집과 상자는 인간과 자연의 공존 가능성을 상징하며, 자연의 생기로운 다양성과 그 안에 내재된 미적 의미를 표현한다.",
        "art_explain_24" : "자연의 온도가 하루 동안 도시의 표면을 지나며 남기는 흔적을 시각화한 작품이다. 새벽의 냉기, 낮의 열기, 저녁의 냉각, 밤의 결정화로 이어지는 네 개의 시퀀스를 통해 자연의 온도와 도시의 표면이 만나는 순간을 표현한다. 반복되는 하루의 온도 순환은 자연이 도시 위에 남기는 보이지 않는 기억과 감각을 드러낸다.",
        "art_explain_25" : "",

        "time_table_title" : "전시 순서 안내",
        "time_table_title_1" : "예술",
        "time_table_title_2" : "동행",
        "time_table_title_3" : "매력",
        "time_table_title_sub_1" : "시작의 근원",
        "time_table_title_sub_2" : "모먼트 서울",
        "time_table_title_sub_3" : "한강 네이처",
        "time_table_art_1" : "1. 이돈아 〈무한한 행복을 향한 여정〉",
        "time_table_art_2" : "2. 최성록 〈서울하늘변신구름많음〉", 
        "time_table_art_3" : "",
        "time_table_art_4" : "3. 서울응원 봄메시지",
        "time_table_art_5" : "4. 해치와 서울나들이",
        "time_table_art_6" : "5. 꼬마 맹꽁이의 모험",
        "time_table_art_7" : "6. 이돈아 〈화조도〉",
        "time_table_art_8" : "7. 최성록 〈기원의 협곡〉",
        "time_table_art_9" : "",
        "time_table_art_10" : "8. 서울응원 봄메시지",
        "time_table_art_11" : "9. 해치와 서울나들이",
        "time_table_art_12" : "10. 꼬마 맹꽁이의 모험",

        "directions_title" : "오시는 길",

        "directions_explain_title_1" : "지하철",
        "directions_explain_title_2" : "버스",
        "directions_explain_title_3" : "자선 버스",

        "directions_explain_1" : "1호선\n용산역 5번출구 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004)\n노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차 -\n노들섬 동측 주차장 방면 진입로 통해 입장\n\n4호선\n신용산역 3번출구 - 도보 100m 위치 신용산역 정류장(03-004) -\n용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차 -\n노들섬 동측 주차장 방면 진입로 통해 입장\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동 - \n노들섬 동측 주차장 방면 진입로 통해 입장\n\n\n",
        "directions_explain_2" : "간선 버스\n150, 151, 152, 500, 504, 506,\n507, 605, 750A, 750B, 751, 752",
        "directions_explain_3" : "지선버스\n6211\n각 버스 하차 후 노들섬 동측 주차장 방면 진입로 통해 입장\n\n한강버스\n여의도 - 압구정 사이 구간에서 관람 가능",
    },
    en : {
        "index_button_introduce" : "About Seoullo Media Canvas",
        "index_button_schedule" : "Schedule",
        "index_button_exhibit" : "Exhibition Introduction",
        "index_button_exhibit_sub" : "",
        "index_button_art_1" : "Emerging Artists Exhibition",
        "index_button_art_1_sub" : "",
        "index_button_art_2" : "Nature Project Exhibition",
        "index_button_art_2_sub" : "",
        // "index_button_directions" : "Location",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        // "atelier_nodeul_name" : "아뜰리에 노들",
        // "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        // "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        // "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<Atelier Nodeul 2026 1st Exhibition : The Origin of All Beginnings> Timeline",
        "schedule_explain_date" : "Exhibition Period | March 22, 2026 (Fri) – July 31, 2026 (Fri)",
        "schedule_explain_pos" : "Venue | Media Façade under the southern pier of Hangang Bridge, \n             Nodeul Island",
        "schedule_explain_pos_detail" : "",
        "schedule_explain_time" : "Screening Hours | 20:00–22:00 (Screened every hour on the hour)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        // "exhibit_intro_title" : "Exhibition Introduction",        
        // "exhibit_introduce_name" : "Atelier Nodeul 2026 1ST EXHIBITION : The Origin of All Beginnings",
        "exhibit_introduce" : "Seoullo Media Canvas is a media art platform that expands the scope of media art by continuously displaying artworks made of electronic light, such as media art and video content that citizens can enjoy and sympathize with.",
        // "exhibit_introduce_sub" : "",
        // "exhibit_explain_name_1" : "The Origin of All Beginnings",
        // "exhibit_explain_1" : "'The Origin of All Beginnings' is a media art exhibition on Nodeul Island, where the lights of the city and the waters of the Hangang River come together.\n\nThrough the dynamic works of two media artists, the exhibition explores moments of origin and creation while highlighting the artistic charm of Nodeul Island and the new possibilities of the Hangang River.",
        // "exhibit_explain_name_2" : "Moment Seoul",
        // "exhibit_explain_2" : "'Moment Seoul' highlights one of Seoul's core values: a compassionate city that walks alongside the vulnerable.\nThrough Spring Message of Support from Seoul, it delivers messages of encouragement to citizens facing new beginnings, while Haechi’s Seoul Journey follows a journey from Nodeul Island to the skies above Seoul, set against the scenery of Nodeul Island and the Hangang River.",
        // "exhibit_explain_name_3" : "Hangang Nature",
        // "exhibit_explain_3" : "'Hangang Nature' represents Seoul's vision of 'Charm', presenting a media-art nature archive of the living ecology of Nodeul Island and the Hangang River.\n\nThrough an omnibus animation featuring the \"Maengkkongi\" the boreal digging frog, as its main character, the work follows a journey in search of a new home, conveying the island's ecology, seasonal changes, and the diverse landscapes of Seoul and the Hangang River.",
        
        "exhibit_2_intro_title" : "Exhibition Introduction",        
        "exhibit_2_introduce_name" : "3rd Exhibition 09.21.-11.30.",
        "exhibit_2_introduce" : "'Seoullo Media Canvas' second exhibition in 2026 welcomes visitors with diverse views of the city, nature, and young creators amid the ripe summer scenery. The exhibition will consist of the Nature Project and the University Cooperation Exhibition, which will showcase the changing landscape of the city, the cycle of nature, and the new generation's sense of looking at it through media art.",
        // "exhibit_2_introduce_sub" : "",
        "exhibit_2_explain_name_1" : "Emerging Artists Exhibition",
        "exhibit_2_explain_1" : "The University Cooperation Exhibition introduces the fresh imagination and experimental gaze of university students who will lead the field of media art in the future. Works that interpret Seoul's daily and seasonal senses, tradition and modernity, and individual memories and emotions in various ways meet with citizens through public media platforms and create a new place of empathy.",
        "exhibit_2_explain_name_2" : "Nature Project Exhibition",
        "exhibit_2_explain_2" : "The Nature Project Exhibition explores the vitality, the passage of time, and the value of recovery and circulation that nature possesses. Works dealing with changes in the four seasons, restoration of ecosystems, records of nature in everyday life, and connectivity from microscopic life to the great universe offer various perspectives on nature and give viewers time to think.",
        // "exhibit_2_explain_name_3" : "Hangang Nature",
        // "exhibit_2_explain_3" : "'Hangang Nature' represents Seoul's vision of 'Charm', presenting a media-art nature archive of the living ecology of Nodeul Island and the Hangang River.\n\nThrough an omnibus animation featuring the \"Maengkkongi\" the boreal digging frog, as its main character, the work follows a journey in search of a new home, conveying the island's ecology, seasonal changes, and the diverse landscapes of Seoul and the Hangang River.",
        
        "link_button_text" : "Watch Video",

        "exhibit_3_introduce" : "The Emerging Artists Exhibition features works by emerging artists in the visual art and video categories, selected through the open call for the “2026 Seoul Media Canvas Emerging Artists Exhibition.”\n\nThe exhibition highlights the diverse artistic practices and creative potential of emerging artists with fresh perspectives and sensibilities. Exploring themes such as personal memories and emotions, everyday landscapes and relationships, nature and the city, and tradition and modernity, the works reinterpret familiar experiences through each artist’s distinctive visual language and modes of expression, revealing the diverse possibilities of media art.",
        "exhibit_4_introduce" : "The Nature Project Exhibition features works selected through the second open call for the “2026 Seoul Media Canvas Nature Project Exhibition.”\n\nThe exhibition explores the diverse relationships between nature, humanity, and the city from new perspectives. Through seasonal landscapes, the cycles of nature, the harmony between traditional motifs and the natural world, and the sensations and traces of nature encountered in everyday urban life, the works offer diverse ways of reconsidering our relationship with nature and invite viewers to pause and reflect.",

        "exhibit_name_1" : "Emerging Artists Exhibition",
        "exhibit_name_2" : "Nature Project Exhibition",

        "exhibit_list_1" : "WALK",
        "exhibit_list_2" : "Five Stories",
        "exhibit_list_3" : "The Luminescence of Memory: Crafting the World in Light",
        "exhibit_list_4" : "Rabbit Moon",
        "exhibit_list_5" : "The Beginning of a Journey",
        "exhibit_list_6" : "Everyone's Long Table-There's One Mpoore Seat",
        "exhibit_list_7" : "Ordinary Day",
        "exhibit_list_8" : "The Flow of Time",
        "exhibit_list_9" : "Dollographic",
        "exhibit_list_10" : "There",
        "exhibit_list_11" : "The longed-for fringetree",
        "exhibit_list_12" : "The Blooming of verdyre",
        "exhibit_list_13" : "Adventures in Starland",
        "exhibit_list_14" : "Dancheong Rain",
        "exhibit_list_15" : "One Strange Afternoon",
        "exhibit_list_16" : "Land of Hope, DMZ",
        "exhibit_list_17" : "Digital Canvas: Evolution of Facades",
        "exhibit_list_18" : "In the Same Boat",
        "exhibit_list_19" : "One, Two, Three!",
        "exhibit_list_20" : "Old Stories",

        "exhibit_list_21" : "Four Seaeons of SEOWON",        
        "exhibit_list_22" : "A Dream of Nacre",
        "exhibit_list_23" : "Relation of Nature",
        "exhibit_list_24" : "Natural Skin",
        "exhibit_list_25" : "",


        "exhibit_artist_name_1" : "KIM JeaMin",
        "exhibit_artist_name_2" : "KIM ARomSaeMi",
        "exhibit_artist_name_3" : "KIM JeongMin",
        "exhibit_artist_name_4" : "KIM JeaN",
        "exhibit_artist_name_5" : "SONG DoYoung",
        "exhibit_artist_name_6" : "SHIN HyeWon",
        "exhibit_artist_name_7" : "ANN SuA",
        "exhibit_artist_name_8" : "Ellie",
        "exhibit_artist_name_9" : "LEE JongHoon",
        "exhibit_artist_name_10" : "JUNG MiJung",
        "exhibit_artist_name_11" : "KIM BoMi\nOH SuA",
        "exhibit_artist_name_12" : "KIM YuMi",
        "exhibit_artist_name_13" : "KIM JeaWon",
        "exhibit_artist_name_14" : "NOH WooYeong",
        "exhibit_artist_name_15" : "NaaveelaB",
        "exhibit_artist_name_16" : "SHIN JongIn",
        "exhibit_artist_name_17" : "LEE YuWoon",
        "exhibit_artist_name_18" : "LEE CheaYoung",
        "exhibit_artist_name_19" : "JANG HyunJi",
        "exhibit_artist_name_20" : "HU Gun",

        "exhibit_artist_name_21" : "KIM DoYoung",        
        "exhibit_artist_name_22" : "KIM LeA",
        "exhibit_artist_name_23" : "CHON SeungIl",
        "exhibit_artist_name_24" : "CHOI MinGyu",
        "exhibit_artist_name_25" : "",


        "art_list_1" : "WALK",
        "art_list_2" : "Five Stories",
        "art_list_3" : "The Luminescence of Memory: Crafting the World in Light",
        "art_list_4" : "Rabbit Moon",
        "art_list_5" : "The Beginning of a Journey",
        "art_list_6" : "Everyone's Long Table-There's One Mpoore Seat",
        "art_list_7" : "Ordinary Day",
        "art_list_8" : "The Flow of Time",
        "art_list_9" : "Dollographic",
        "art_list_10" : "There",
        "art_list_11" : "The longed-for fringetree",
        "art_list_12" : "The Blooming of verdyre",
        "art_list_13" : "Adventures in Starland",
        "art_list_14" : "Dancheong Rain",
        "art_list_15" : "One Strange Afternoon",
        "art_list_16" : "Land of Hope, DMZ",
        "art_list_17" : "Digital Canvas: Evolution of Facades",
        "art_list_18" : "In the Same Boat",
        "art_list_19" : "One, Two, Three!",
        "art_list_20" : "Old Stories",

        "art_list_21" : "Four Seaeons of SEOWON",        
        "art_list_22" : "A Dream of Nacre",
        "art_list_23" : "Relation of Nature",
        "art_list_24" : "Natural Skin",
        
        "art_list_25" : "",


        "artist_name_1" : "KIM JeaMin",
        "artist_name_2" : "KIM ARomSaeMi",
        "artist_name_3" : "KIM JeongMin",
        "artist_name_4" : "KIM JeaN",
        "artist_name_5" : "SONG DoYoung",
        "artist_name_6" : "SHIN HyeWon",
        "artist_name_7" : "ANN SuA",
        "artist_name_8" : "Ellie",
        "artist_name_9" : "LEE JongHoon",
        "artist_name_10" : "JUNG MiJung",
        "artist_name_11" : "KIM BoMi\nOH SuA",
        "artist_name_12" : "KIM YuMi",
        "artist_name_13" : "KIM JeaWon",
        "artist_name_14" : "NOH WooYeong",
        "artist_name_15" : "NaaveelaB",
        "artist_name_16" : "SHIN JongIn",
        "artist_name_17" : "LEE YuWoon",
        "artist_name_18" : "LEE CheaYoung",
        "artist_name_19" : "JANG HyunJi",
        "artist_name_20" : "HU Gun",

        "artist_name_21" : "KIM DoYoung",        
        "artist_name_22" : "KIM LeA",
        "artist_name_23" : "CHON SeungIl",
        "artist_name_24" : "CHOI MinGyu",
        "artist_name_25" : "",


        "art_explain_1" : "In the work, I begin each day once again as a fisherman.\nToday, I go out to sea to catch fish, and tomorrow and the day after, I will live the same day over again.\nIn the midst of a repetitive life without a clear purpose, are we truly able to live without losing our sense of self?\nThe image of myself, with the head of a fish, catching fish reflects the way we ultimately find ourselves holding on to beings that resemble us within the repetition of everyday life.\nPerhaps the fish I pull from the water is a reflection of ourselves, swimming through the sea without knowing our direction or purpose.",
        "art_explain_2" : "The artist depicts an inner world called “Aroan.”\nAfter experiencing the collapse of their inner world following the death of a younger sibling, the artist began reinterpreting their inner state through imagery and recording it in pen.\nThe five stories are composed of five interconnected drawings.\nAlthough each frame presents an entirely different image, the drawings are subtly connected to one another, conveying a narrative about the passage of time.\nThe work records events that unfold over time through encounters with new people and new situations.",
        "art_explain_3" : "'This work is a special “Planet of Memories,” created by layering rainbow-colored hanji (traditional Korean paper) to depict places tied to cherished memories, including Seoul, Pohang, Namhae, and Laos, where the artist volunteered.\nPaint is applied to the hanji and allowed to soak into the paper, creating a shimmering, mother-of-pearl-like effect.\nJust as each person has a different and beautiful color within their heart, the work brings together fragments of positive memories to convey a beautiful world and a warm landscape that each of us can carry within.",
        "art_explain_4" : "<Rabbit Moon> tells the story of a moon rabbit who creates stars from people’s wishes.\nLiving alone on the moon, the moon rabbit sets off on a journey to Earth in search of a new world and new friends.\nAs the rabbit draws closer to Earth, the vibrant colors gradually fade away, revealing a black-and-white world of doodles.\nTraveling through this unfamiliar world, the moon rabbit discovers others and learns the joy of being together.\nA small wish that began on the moon becomes a star, and the moon rabbit’s journey unfolds into another new story on Earth.",
        "art_explain_5" : "The tiger lying atop a bottle journeys through vast wilderness, snowy fields, dark forests, and spaces filled with overwhelming fear.\nAlthough the tiger itself remains largely unchanged, the world it encounters and the beings around it are constantly shifting.\nThrough an animal fable, the work explores the possibility of facing the world again, forming new connections, and continuing to live despite failure and fear.",
        "art_explain_6" : "Animal friends, each having spent a different kind of day, gather around a long table, bringing food and stories to share.\nDifferent moments, like sunlight, raindrops, and starlight, naturally come together over a shared meal as the friends pass bread and make room for one another.\nThe empty chair left at the end of the table is an invitation to the citizens watching the screen.\nThe work conveys the hope that Seoul can become a warmer and more vibrant city when everyone is welcomed and comes together.",
        "art_explain_7" : "The artist records the movements of people, birds, and plants that pass by in everyday life, then reconstructs captured moments as paintings.\nThe figures within the frame were already moving before they were captured and will continue on their way even after they leave the frame.\nBy layering traces of movement, the work conveys the uninterrupted continuity of everyday life within the canvas.\nIt reflects on the inherent value of simply living through the ordinary moments of daily life.",
        "art_explain_8" : "The work depicts a single place transforming across three eras: prehistoric times, the Joseon Dynasty, and the present day.\nGuided by a tiger, a symbol of the Korean people, viewers are invited to appreciate the striking contrast between timeless nature and the evolution of civilization.\nPlayful elements that transcend time and space are hidden throughout the work, including a turtle ship and a cruise boat on the river, as well as a pterosaur and an airplane flying through the sky.\nThe work invites viewers on a journey through time where the past and present coexist.",
        "art_explain_9" : "<Dollographic> is a work in which stones of different shapes are carefully examined and arranged to resemble the consonants and vowels of Hangul, the Korean alphabet.\nSmall stones come together to form letters, and the letters connect to create a sentence.\nBy bringing together the natural forms of stones and the Hangul characters we use every day, the work offers the joy of seeing familiar letters from a new perspective.",
        "art_explain_10" : "Past experiences are remembered over time in ways that may or may not correspond to what actually happened, shaping the visual images that emerge from those memories.\nElements such as buildings, light, and passing people intertwine and separate, forming an overall image that feels both familiar and unfamiliar.\nBased on the temporality of the work, “memory” is translated into visual imagery that evokes a simultaneous sense of familiarity and strangeness.",
        "art_explain_11" : "Inspired by Arbor Day, the work metaphorically represents a tree that has been cut down through the protagonist’s short hair.\nLonging for the wholeness of her former self, the protagonist plants a new fringe tree, sincerely hoping that this tree, at least, will grow straight and strong without being broken.\nMoving beyond the pain of loss, the work places hope in new life and conveys a message of healing through the cycle of nature and a hopeful vision for the future.",
        "art_explain_12" : "This work began with the imagination that a miniature world of nature might be hidden within the Baekje Gilt-bronze Incense Burner.\nInspired by the mountains and animals depicted on the incense burner, particularly the deer, the work reimagines them as a mother-of-pearl-like deer and a luminous, futuristic garden.\nAt the end, traditional Korean lattice doors open to reveal the Baekje Gilt-bronze Incense Burner, showing that the world of light seen throughout the work was an imagined world originating from the incense burner.\nThe work conveys the idea of ancient cultural heritage blooming anew through an encounter with the light and technology of today.",
        "art_explain_13" : "<Adventures in Starland> is a magical world where day and night, land and sea, are all connected as one.\nAnimals of different appearances and habitats—including lions, zebras, swimming whales, and flying birds—gather in one place and move together peacefully.\nSeeing the animals moving forward together in harmony, rather than alone, brings a sense of warmth.\nThe work conveys the message that even though we are different, we are happiest when we live together in harmony.",
        "art_explain_14" : "<Dancheong Rain> is a public media art piece inspired by the colors and patterns of traditional Korean dancheong.\nDrawing on the sensation of raindrops falling from the edges of traditional eaves, the work combines the colors and patterns of dancheong with the flow of rain, transforming them into new forms of movement.\nFragments of color and pattern scatter and fall like rain, creating a repetitive rhythm.\nThrough this process, the work expands tradition beyond a fixed image into a sensory experience newly encountered through time and movement.",
        "art_explain_15" : "Giant ears of corn and slightly peculiar mushroom-like creatures appear. Corn leaves become tiny boats that fly through the sky, while small travelers born atop mushrooms rise toward a world above the clouds.\nImagining another world hidden within ordinary nature, the work depicts a strange afternoon where the boundaries between reality and imagination are freely crossed by creatures that could be alpacas, mushrooms, or perhaps something in between.",
        "art_explain_16" : "The 80 years of division that began at the 38th parallel in 1945 have passed through war and barbed wire, and now continue into a time of forests and renewed life.\nThousands of fireflies trace paths of light over the barbed wire erected by humans, gradually erasing the boundaries.\nThrough life that has grown again over the ruins, the work poetically portrays the hope for healing and connection beyond division.",
        "art_explain_17" : "This work transforms more than 20 years of ink paintings depicting historic architecture into digital images, reconstructing them as a moving visual composition.\nModern architectural landmarks in Seoul, including Seoul Station, the Bank of Korea, and the former Gyeongseong Post Office, are layered together with traditional Korean hanok houses and European Gothic cathedrals, creating a new urban landscape that transcends time and space.\nBy combining traditional ink painting with digital media, the work invites viewers to see the architecture of the past and the city of today from a new perspective.",
        "art_explain_18" : "A single boat floats on a foggy sea at night. The five women guarding the boat all have the same face.\nThe five never wake at the same time, yet they care for one another through the water and ropes left behind by the others.\nOne night, an unknown signal rises from beneath the water. For the first time, all five awaken together and pull on a single rope.\nOnly then does the rope, which would not move when pulled alone, finally begin to give.\nIt is a story about the many “selves” within us caring for one another.",
        "art_explain_19" : "<One, Two, Three!> is a 3D animation that follows the small adventure of three adorable baby rabbits.\nThe rabbits head to a field to steal some carrots, but after encountering a mysterious giant shadow, they run away. When one of their friends goes missing, however, they gather their courage and return to the field to rescue their friend.\nWith charming characters, playful scenes, and an unexpected twist, the work offers an entertaining experience while warmly conveying a message of friendship, courage, and growth—the idea that even frightening moments can be overcome when faced together with friends.",
        "art_explain_20" : "\"Godam, Old Stories\" literally means \"old tales.\"\nKorean folk paintings, or minhwa, are rich with stories. Since ancient times, people have believed that magpies in minhwa bring good news for the New Year, while tigers painted alongside them ward off negative energy.\nPeonies, depicted in full and splendid bloom, have long symbolized wealth and happiness.\nThrough this work, the artist imagines a woman from a traditional Korean beauty painting leading viewers into the world of minhwa, as though unfolding a bundle of old stories.",

        "art_explain_21" : "This work expands the four seasonal landscapes of Korean seowon (Confucian academies), created in traditional Korean color painting, into motion graphics.\nThrough the plum blossoms of Dosan Seowon, crape myrtles of Namgye Seowon, ginkgo trees of Dodong Seowon, and pine trees of Sosu Seowon, the work expresses a distinctly Korean aesthetic in which nature and hanok architecture exist in harmony, along with the beauty of stillness within movement.\nBy combining Hangul typography inspired by the forms of hanok with poetic language, the work invites viewers to slowly contemplate the emotions and landscapes of each season.",
        "art_explain_22" : "This work begins with a moon jar made from earth and mother-of-pearl sourced from nature, reinterpreting symbolic elements from traditional Korean folk painting (minhwa) through contemporary media art.\nA dreamlike landscape unfolds through shimmering mother-of-pearl waterfalls and waves, fish, deer, cranes, and a white tiger, expressing the flourishing of life, the cycle of nature, and a peaceful ideal world.\nThe reflective qualities of mother-of-pearl and the organic flow of color create a sensory experience that moves between the boundaries of reality and dreams.",
        "art_explain_23" : "This media art work explores the beauty and warmth of nature, as well as the relationship between humans and the natural world.\nIt begins from the perspective that nature is not simply a landscape, but a living environment with which humans have formed a deep and enduring relationship over time.\nThe house and box depicted in the work symbolize the possibility of coexistence between humans and nature, while expressing nature’s vibrant diversity and the aesthetic meaning inherent within it.",
        "art_explain_24" : "This work visualizes the traces left by nature’s changing temperatures as they pass across the surfaces of the city throughout a single day.\nThrough four sequences—the chill of dawn, the heat of daytime, the cooling of evening, and the crystallization of night—the work captures moments when natural temperatures encounter urban surfaces.\nThe recurring daily cycle of temperature reveals the invisible memories and sensations that nature leaves behind upon the city.",
        "art_explain_25" : "",

        // "time_table_title" : "Information",
        // "time_table_title_1" : "Art",
        // "time_table_title_2" : "DongHaeng\n(empathy)",
        // "time_table_title_3" : "MaeRyeok\n(charming)",
        // "time_table_title_sub_1" : "The Origin of All Beginnings",
        // "time_table_title_sub_2" : "Moment Seoul",
        // "time_table_title_sub_3" : "Hangang Nature",
        // "time_table_art_1" : "1. Lee Donah 〈Odyssey to Infinite Happiness〉",
        // "time_table_art_2" : "2. Choi Sungrok 〈Seoul Sky of Transforming Clouds〉",
        // "time_table_art_3" : "",
        // "time_table_art_4" : "3. Spring Message of Support from Seoul",
        // "time_table_art_5" : "4. Haechi's Seoul Journey",
        // "time_table_art_6" : "5. Little Maengkkongi's Adventure",
        // "time_table_art_7" : "6. Lee Donah 〈Hwajodo in Space〉",
        // "time_table_art_8" : "7. Choi Sungrok 〈Genesis Canyon〉",
        // "time_table_art_9" : "",
        // "time_table_art_10" : "8. Spring Message of Support from Seoul",
        // "time_table_art_11" : "9. Haechi's Seoul Journey",
        // "time_table_art_12" : "10. Little Maengkkongi's Adventure",

        // "directions_title" : "Location",

        // "directions_explain_title_1" : "Subway",
        // "directions_explain_title_2" : "Bus",
        // "directions_explain_title_3" : "Green Bus (Local Route)",

        // "directions_explain_1" : "Line 1\nYongsan Station - Exit 5 → Walk about 300m to Yongsan Station\nBus Stop (03-004) → Take a bus toward Nodeul Island → Get off at\nNodeul Island Stop (03-340) → Enter via the access road next to the East Parking Gate\n\nLine 4\nSinyongsan Station – Exit 3 → Walk 100m to Sinyongsan Station\nBus Stop (03-004) → Take a bus toward Yongsan / Nodeul Island →\nContinue toward Hangang Bridge for about 700m → Get off at Nodeul Island Stop (03-340) → Enter via the access road next to the East Parking Gate\n\nLine 9\nNodeul Station - Exit 2 → Walk approximately 700m toward\nHangang Bridge → Enter via the access road next to the East Parking Gate\n",
        // "directions_explain_2" : "Blue Bus (Main Routes)\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752",
        // "directions_explain_3" : "6211\n→ Get off and enter via the access road next to the East Parking Gate\n\nHangang Bus\nThe exhibition is visible while riding between Yeouido and Apgujeong.",
    },
    ja : {
        "index_button_introduce" : "(일본어)아뜰리에 노들 소개",
        "index_button_schedule" : "(일본어)상영 시간표",
        "index_button_exhibit" : "(일본어)예술 미디어스케이프",
        "index_button_exhibit_sub" : " ",
        "index_button_art_1" : "(일본어)동행 모먼트서울",
        "index_button_art_1_sub" : " ",
        "index_button_art_2" : "(일본어)매력 한강네이처",
        "index_button_art_2_sub" : " ",
        
        "back_button_text" : "BACK",
        "top_button_text" : "(일본어)Top",
        "list_button_text" : "list",
        "prev_button_text" : "(일본어)이전",
        "next_button_text" : "(일본어)다음",

        "schedule_explain_name" : "(일)아뜰리에노들 미디어아트 상영 시간표",
        "atelier_nodeul_name" : "(일본어)아뜰리에 노들",
        "atelier_nodeul_explain" : "(일본어)아뜰리에 노들 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "schedule_name" : "(일)작품명",
        "schedule_time" : "(일)상영 시간",

        "exhibit_title" : "(일본어)전시 소개",        
        "exhibit_introduce" : "(일본어)전시 소개\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        "exhibit_explain" : "(일본어)전시 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "link_button_text" : "(일본어)영상 보러가기",

        "exhibit_name_1" : "(일)예술: 미디어스케이프 (Mediascape)",
        "artist_name_1" : "(일본어)작가명1",
        "art_name_1" : "(일본어)작품명1",
        "art_explain_1" : "(일본어)작품 설명1\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_2" : "(일본어)전시명2",
        "artist_name_2" : "(일본어)작가명2",
        "art_name_2" : "(일본어)작품명2",
        "art_explain_2" : "(일본어)작품 설명2\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_3" : "(일본어)전시명3",
        "artist_name_3" : "(일본어)작가명3",
        "art_name_3" : "(일본어)작품명3",
        "art_explain_3" : "(일본어)작품 설명3\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",

        "directions_explain" : "(일)지하철\n1호선\n용산역 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004) 노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번 출구 - 도보 100m 위치 신용산역 정류장(03-004) 용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n\n버스\n간선 버스\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\n자선 버스\n6211"
    }
    
}
