const translations = {
    ko: {
        "index_button_introduce" : "서울로미디어캔버스 소개",
        "index_button_schedule" : "상영 시간표",
        "index_button_exhibit" : "전시 소개",
        "index_button_exhibit_sub" : "",
        "index_button_art_1" : "대학협력전",
        "index_button_art_1_sub" : "",
        "index_button_art_2" : "네이처 프로젝트전",
        "index_button_art_2_sub" : "",
        "index_button_directions" : "오시는 길",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        // "atelier_nodeul_name" : "아뜰리에 노들",
        // "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        // "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        // "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<아뜰리에 노들 2026 첫 번째 전시 : 시작의 근원> 전시 시간표",
        "schedule_explain_date" : "전시 기간: 2026.05.22.(금) ~ 2026.07.31.(금)",
        "schedule_explain_pos" : "상영 장소: 노들섬 남단 한강대교 교각 하부 미디어파사드",
        "schedule_explain_pos_detail" : "노들섬 아트라운지 미디어볼 상명 시간",
        "schedule_explain_time" : "상영 시간: 20:00 ~ 22:00 (매 시각 정시 상영)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        // "exhibit_intro_title" : "전시 소개",        
        // "exhibit_introduce_name" : "2026 아뜰리에 노들 첫 전시 : 시작의 근원\nAtelier Nodeul 2026 1st Exhibition : The Origin of All Beginnings",
        "exhibit_introduce" : "서울로미디어캔버스는 시민이 향유하고 공감할 수 있는\n미디어아트와 영상 콘텐츠 등 전자적 빛으로 이루어진\n예술작품을 지속 전시하여 미디어아트의 영역을 확장하는\n미디어아트 전문 플랫폼입니다.",
        // "exhibit_introduce_sub" : "*특정 지역이나 환경을 대표하면서 사람들의 관심과 보호의식을 이끌어내기 위해 선정된 상징적인 생물종",
        // "exhibit_explain_name_1" : "시작의 근원",
        // "exhibit_explain_1" : "'시작의 근원 The Origin of All Beginnings'은 한강 노들섬에서 펼쳐지는 미디어아트 전시로, 도시의 빛과 물결이 교차하는 지점에서 기원과 생성의 순간을 탐구합니다.\n이돈아, 최성록 두 미디어아티스트의 다채롭고 역동적인 작품을 통해 노들섬의 예술적 매력과 한강의 새로운 가능성을 재조명합니다.",
        // "exhibit_explain_name_2" : "모먼트 서울",
        // "exhibit_explain_2" : "서울의 핵심 가치인 ‘약자와 동행하는 상생 도시’를 강조합니다.\n〈서울응원 메시지〉를 통해 새로운 시작을 앞둔 시민들에게 응원의 메시지를 전달하고, 〈해치와 서울나들이〉는 노들섬과 한강변을 배경으로, 노들섬에서 출발해 서울 상공으로 이어지는 여정을 그립니다.",
        // "exhibit_explain_name_3" : "한강 네이처",
        // "exhibit_explain_3" : "한강 네이처는 서울의 비전인 ‘매력’을 상징하며, 자연이 살아 숨 쉬는 한강 노들섬의 생태를 미디어아트로 풀어낸 자연도감입니다.\n맹꽁이를 주인공으로 한 옴니버스 애니메이션으로, 새로운 터전을 찾아가는 여정을 통해 노들섬의 생태와 계절의 변화, 그리고 서울과 한강의 다양한 모습을 전합니다.",
        
        "exhibit_2_intro_title" : "전시 소개",        
        "exhibit_2_introduce_name" : "두 번째 전시 07.01.-09.19.",
        "exhibit_2_introduce" : "서울로미디어캔버스의 2026년 두 번째 전시는 무르익은\n여름의 풍경 속에서 도시와 자연, 그리고 청년 창작자들의\n다양한 시선을 담아 관람객을 맞이합니다. 이번 전시는\n네이처프로젝트전과 대학협력전으로 구성되며, 변화하는\n도시의 풍경과 자연의 순환, 그리고 이를 바라보는 새로운\n세대의 감각을 미디어아트로 선보입니다.",
        // "exhibit_2_introduce_sub" : "*특정 지역이나 환경을 대표하면서 사람들의 관심과 보호의식을 이끌어내기 위해 선정된 상징적인 생물종",
        "exhibit_2_explain_name_1" : "대학협력전",
        "exhibit_2_explain_1" : "대학협력전은 미래의 미디어아트 분야를 이끌어갈 대학생\n작가들의 참신한 상상력과 실험적인 시선을 소개합니다. 서울의\n일상과 계절의 감각, 전통과 현대, 개인의 기억과 감정을 다채로운 방식으로 해석한 작품들은 공공 미디어 플랫폼을 통해 시민들과\n만나며 새로운 공감의 장을 만들어냅니다.",
        "exhibit_2_explain_name_2" : "네이처 프로젝트전",
        "exhibit_2_explain_2" : "네이처 프로젝트전은 자연이 품고 있는 생명력과 시간의 흐름,\n그리고 회복과 순환의 가치를 탐구합니다. 사계절의 변화와\n생태계의 회복, 일상 속 자연의 기록, 그리고 미시적 생명에서\n거대한 우주로 이어지는 연결성을 다룬 작품들은 자연을 바라보는 다양한 관점을 제시하며 관람객들에게 사유의 시간을 선사합니다.",
        // "exhibit_2_explain_name_3" : "한강 네이처",
        // "exhibit_2_explain_3" : "한강 네이처는 서울의 비전인 ‘매력’을 상징하며, 자연이 살아 숨 쉬는 한강 노들섬의 생태를 미디어아트로 풀어낸 자연도감입니다.\n맹꽁이를 주인공으로 한 옴니버스 애니메이션으로, 새로운 터전을 찾아가는 여정을 통해 노들섬의 생태와 계절의 변화, 그리고 서울과 한강의 다양한 모습을 전합니다.",
        
        "link_button_text" : "영상 보러가기",

        "exhibit_name_1" : "대학협력전",
        "exhibit_name_2" : "네이처 프로젝트전",

        "exhibit_list_1" : "유영",
        "exhibit_list_2" : "하루가 구워지는 곳",
        "exhibit_list_3" : "잠상",
        "exhibit_list_4" : "마음의 꽃잎",
        "exhibit_list_5" : "네모난 방 안에서 네모난 여름",
        "exhibit_list_6" : "여름휴가",
        "exhibit_list_7" : "말",
        "exhibit_list_8" : "각자의 방식으로",
        "exhibit_list_9" : "창 너머",
        "exhibit_list_10" : "달콤한 여름",
        "exhibit_list_11" : "자개가 펼처지는 순간",
        "exhibit_list_12" : "소원",
        "exhibit_list_13" : "유월의 하루",
        "exhibit_list_14" : "동화 이야기",
        "exhibit_list_15" : "빛의 깊은 물결",
        "exhibit_list_16" : "천문",
        "exhibit_list_17" : "서울 소울메이트",
        "exhibit_list_18" : "경계",
        "exhibit_list_19" : "흐르는 서울",
        "exhibit_list_20" : "서울을 가로지르는 바람",
        "exhibit_list_21" : "침입",
        
        "exhibit_list_22" : "사계",
        "exhibit_list_23" : "오랜만이야!",
        "exhibit_list_24" : "오늘도, 그 산은",
        "exhibit_list_25" : "세포에서 은하까지",


        "exhibit_artist_name_1" : "황세희",
        "exhibit_artist_name_2" : "전수아",
        "exhibit_artist_name_3" : "박지현",
        "exhibit_artist_name_4" : "김서운",
        "exhibit_artist_name_5" : "권예지",
        "exhibit_artist_name_6" : "김소정",
        "exhibit_artist_name_7" : "박규리",
        "exhibit_artist_name_8" : "이여진",
        "exhibit_artist_name_9" : "양이삭",
        "exhibit_artist_name_10" : "최수빈",
        "exhibit_artist_name_11" : "강지수",
        "exhibit_artist_name_12" : "이혜진",
        "exhibit_artist_name_13" : "이채현",
        "exhibit_artist_name_14" : "원유경",
        "exhibit_artist_name_15" : "이소형",
        "exhibit_artist_name_16" : "김단아\n이채린\n정유경",
        "exhibit_artist_name_17" : "김나현\n김도향\n황신영",
        "exhibit_artist_name_18" : "권수진\n김지연\n박예림",
        "exhibit_artist_name_19" : "송찬영\n유지혜\n차시은",
        "exhibit_artist_name_20" : "진가려\n추운가\n리신",
        "exhibit_artist_name_21" : "김송림\n남유연\n은수안\n조나연",
        
        "exhibit_artist_name_22" : "김영우",
        "exhibit_artist_name_23" : "나나",
        "exhibit_artist_name_24" : "장철원",
        "exhibit_artist_name_25" : "최인종",

        "art_list_1" : "<유영(游泳)>",
        "art_list_2" : "<하루가 구워지는 곳>",
        "art_list_3" : "<잠상(潛像)>",
        "art_list_4" : "<마음의 꽃잎>",
        "art_list_5" : "<네모난 방 안에서 네모난 여름>",
        "art_list_6" : "<여름휴가>",
        "art_list_7" : "<말>",
        "art_list_8" : "<각자의 방식으로>",
        "art_list_9" : "<창 너머>",
        "art_list_10" : "<달콤한 여름>",
        "art_list_11" : "<자개가 펼처지는 순간>",
        "art_list_12" : "<소원>",
        "art_list_13" : "<유월의 하루>",
        "art_list_14" : "<동화 이야기>",
        "art_list_15" : "<빛의 깊은 물결>",
        "art_list_16" : "<천문>",
        "art_list_17" : "<서울 소울메이트>",
        "art_list_18" : "<경계>",
        "art_list_19" : "<흐르는 서울>",
        "art_list_20" : "<서울을 가로지르는 바람>",
        "art_list_21" : "<침입>",
        
        "art_list_22" : "<사계>",
        "art_list_23" : "<오랜만이야!>",
        "art_list_24" : "<오늘도, 그 산은>",
        "art_list_25" : "<세포에서 은하까지>",


        "artist_name_1" : "황세희",
        "artist_name_2" : "전수아",
        "artist_name_3" : "박지현",
        "artist_name_4" : "김서운",
        "artist_name_5" : "권예지",
        "artist_name_6" : "김소정",
        "artist_name_7" : "박규리",
        "artist_name_8" : "이여진",
        "artist_name_9" : "양이삭",
        "artist_name_10" : "최수빈",
        "artist_name_11" : "강지수",
        "artist_name_12" : "이혜진",
        "artist_name_13" : "이채현",
        "artist_name_14" : "원유경",
        "artist_name_15" : "이소형",
        "artist_name_16" : "김단아 이채린 정유경",
        "artist_name_17" : "김나현 김도향 황신영",
        "artist_name_18" : "권수진 김지연 박예림",
        "artist_name_19" : "송찬영 유지혜 차시은",
        "artist_name_20" : "진가려 추운가 리신",
        "artist_name_21" : "김송림 남유연 은수안 조나연",
        
        "artist_name_22" : "김영우",
        "artist_name_23" : "나나",
        "artist_name_24" : "장철원",
        "artist_name_25" : "최인종",
        
        "art_explain_1" : "⟨유영(游泳)⟩은 코스모스 꽃밭 아래에서 하늘을 바라보며, 천천히 흐르는 구름과 바람에 흔들리는 꽃들의 움직임을 생동감 있게 담아낸 작품이다.\n\n6월의 초여름은 생명이 가장 선명하게 숨 쉬는 계절이다.\n푸른 하늘 아래 펼쳐진 코스모스 들판에 누워, 마치 여름 속을 유영하듯 그 순간의 공기와 흐름을 온전히 체감하게 된다.\n\n빠르게 흘러가는 도심의 일상 속에서 잠시 걸음을 멈추고, 현대인들이 무심히 지나치던 하늘과 계절의 감각에 천천히 몰입할 수 있도록 한다.\n\n잔잔히 흐르는 6월의 순간을 유영하듯.",
        "art_explain_2" : "빠르게 흘러가는 서울의 일상 속에서 사람들은 끊임없이 움직이며 여유를 잃기 쉽다.\n작가 역시 바쁜 생활 속에서 잠시 쉬어갈 시간이 부족하다고 느껴, 이러한 경험을 바탕으로 따뜻한 휴식의 공간을 표현하고자 했다.\n\n그래서 현실과 다른 속도로 시간이 흐르는 ‘쥐들의 애플파이 가게’를 컨셉으로 설정했다.\n작은 쥐들이 천천히 애플파이를 굽고 피크닉을 즐기는 모습을 통해 느리고 포근한 시간을 담았으며, 굴러온 사과에 놀라 분주하게 움직이는 장면으로 잔잔한 일상 속 작은 활기를 더했다.\n\n이 작품이 바쁜 일상 속에서 잠시 멈춰 여유와 힐링을 떠올릴 수 있는 작은 쉼표가 되기를 바란다.",
        "art_explain_3" : "'잠상(潛像)'은 사진 용어로, 필름에 기록되어 있지만 아직 눈에 보이지 않는 이미지를 의미한다.\n이 작품은 이러한 개념을 꿈과 기억의 이미지에 연결하여 표현한 패턴 기반 미디어 작업이다.\n\n영상 속 꽃의 형태와 패턴은 반복되고 확장되며 끊임없이 변화한다. 흐릿한 형상은 잠시 선명하게 드러났다가 다시 사라지고, 서로 다른 이미지들은 겹쳐지며 새로운 장면을 만들어낸다.\n반복적으로 변화하는 패턴은 꿈속에서 떠오르는 기억의 조각들과 감정의 흐름을 상징한다.\n\n우리는 꿈속에서 현실의 기억과 감정, 익숙한 장면들이 예상치 못한 모습으로 나타나는 경험을 하곤 한다. 작품은 이러한 꿈의 특성을 패턴과 움직임으로 시각화하며, 보이지 않던 이미지가 떠오르고 사라지는 순간을 담아낸다.\n\n관람자는 끊임없이 변화하는 형상과 흐름 속에서 꿈과 기억의 잔상을 따라가며, 자신만의 감정과 상상을 마주하게 된다.",
        "art_explain_4" : "눈에 보이지 않는 감정의 흐름을 유기적인 꽃의 형태와 부드러운 움직임으로 표현한 미디어 아트 작품이다.\n\n우리는 일상 속에서 기쁨, 불안, 설렘, 평온 등 다양한 감정을 경험하며 살아간다. 하지만 감정은 하나의 형태로 정의되지 않고 서로 섞이며 끊임없이 변화한다.\n이 작품은 이러한 감정의 흐름을 추상적인 꽃의 형상과 자연스러운 움직임으로 시각화하였다.\n\n꽃의 형태는 피어나고 흩어지기를 반복하며 감정이 생성되고 변화하는 과정을 상징한다.\n서로 겹쳐지고 이어지는 유기적인 움직임은 감정이 시간의 흐름 속에서 변화하고 순환하는 모습을 담고 있다.\n\n또한 형태와 질감이 만들어내는 부드러운 흐름을 통해 눈에 보이지 않는 감정의 움직임을 표현하고자 하였다.\n끊임없이 변화하는 꽃의 형상은 복잡한 감정들이 하나의 흐름 안에서 피어나고 사라지는 과정을 보여주며, 형태 없는 내면의 감정을 시각적으로 풀어낸다.",
        "art_explain_5" : "여름하면 생각나는 바다, 바쁜 나날들로 직접 가지 못해도 방 안에서 수족관 장난감에 담긴 바다를 즐길 수 있다.\n작고 네모난 영역에서 전개되는 바다를 멍하니 바라보다 보면 시간 가는 줄 모른다.\n\n마치 서울로 미디어의 네모난 스크린에서, 네모난 방 안에 있는, 네모난 수족관을 바라보는 것처럼.",
        "art_explain_6" : "여름 휴가는 답답하고 빠르게 흘러가는 도심의 소란스러운 일상 속에서, 온전한 해방감을 찾아 떠나는 여정을 담은 영상이다.\n\n네온사인으로 가득한 삭막한 도시의 야경을 지나 화면이 전환되면, 시원한 칵테일 한 잔과 함께 에메랄드빛 푸른 바다가 눈앞에 펼쳐진다.\n\n야근과 힘든 일상 속에서 벗어나 누구나 한 번쯤 꿈꾸는 이국적이고 평화로운 공간으로 이동한다. 낮과 밤을 관통하며 펼쳐지는 휴양지의 풍경은 갇혀 있던 답답함을 해소하고 꿈꾸는 것 같은 공간으로 넘어가 지친 일상을 벗어난다는 해방감을 선사한다.",
        "art_explain_7" : "2026년 병오년, 말의 해를 맞아 다양한 생김새의 말들이 각자의 걸음으로 화면을 가로지르는 영상을 제작했다.\n영상 속 말들은 반복되는 일상 속에서도 각자의 방향을 향해 끊임없이 움직이며 살아가는 우리들의 모습을 상징한다. 어떤 말은 빠르게 달리고, 어떤 말은 천천히 걸어간다. 크기와 형태, 속도는 모두 다르지만 모든 말들은 저마다의 리듬으로 앞으로 나아간다.\n\n우리는 종종 타인의 속도와 방향을 기준 삼아 스스로를 비교하며 살아간다. 하지만 이 작품은 서로 다른 모습과 속도를 가진 존재들이 같은 화면 안에서 함께 움직이는 모습을 통해, 각자의 방식대로 살아가는 삶 자체에 의미가 있음을 이야기하고자 했다.\n\n영상 속 말들은 정해진 목적지 없이 계속해서 움직인다. 이는 바쁘게 흘러가는 현대 사회 속에서 끊임없이 앞으로 나아가야 하는 우리의 모습과 닮아있다. 모두가 같은 길을 걷고 있지는 않지만, 각자의 자리에서 자신만의 방향을 향해 묵묵히 나아가고 있다는 점만큼은 같다.\n\n이 작품은 서로 다른 속도와 형태를 가진 존재들이 한 공간 안에서 함께 흐르는 장면을 통해, 각자의 삶의 방향성과 움직임에 대해 다시 바라보고자 제작한 작업이다.",
        "art_explain_8" : "도시를 살아가는 젤리곰들은 모두 같은 모습으로 태어났지만, 각자가 마주한 환경에 따라 전혀 다른 삶을 살아간다.\n뜨거운 빛 아래 녹아내리기도 하고, 위험을 피해 움직이기도 하며, 때로는 변화한 모습 그대로 새로운 환경에 적응하기도 한다.\n\n이 작품은 도시라는 공간을 축소된 사회로 바라보며, 같은 조건에서 시작하더라도 환경에 따라 달라지는 존재들의 다양한 생존 방식을 표현한다.",
        "art_explain_9" : "밤이 내려앉은 작은 방 안, 무료함에 잠겨 있던 소년 앞에 작은 종이비행기 하나가 날아든다. 소년은 망설임 없이 종이비행기를 따라 움직이고, 결국 창밖으로 몸을 던질 만큼 충동적인 행동을 보인다.\n\n그 순간, 곁에 있던 인물은 급하게 소년을 붙잡으며 짧은 위기의 순간을 함께 마주하게 된다.\n\n본 작품은 ʻPROJECT : SHOMA’ 세계관을 기반으로 제작된 3D 아나몰픽 미디어파사드 영상으로, 두 인물간의 관계성과 행동으로 드러나는 성격 차이, 감정의 흐름을 짧은 서사 안에 담아내고자 하였다.\n\n영상은 지루함에서 시작해 호기심, 몰입, 긴장, 안도감, 여운으로 이어지는 감정 구조를 기반으로 구성되었으며, 고정된 카메라와 원테이크 형식을 통해 공간의 연속성과 몰입감을강조하였다. 또한 배경 속 액자와 도시 풍경등 다양한 시각적 요소를 통해 작품 세계관의 일부를 암시적으로 표현하였다.",
        "art_explain_10" : "'여름'과 '동심'을 키워드로 하여 도심의 공간을 청량한 상상들로 환기시킨다.\n\n중력을 거슬러 공중을 가르는 거대한 미끄럼틀, 떠다니는 구름을 만져보고 솜사탕처럼 맛보는 행위, 수많은 풍선들을 타고 하늘을 유영하는 기구, 아이스크림으로 된 벽을 맛보기도 하는 등 어릴 적 누구나 한 번쯤 꿈꾸었던 환상을 그린다.\n\n여름의 파란 하늘과 그 속을 유영하는 곰젤리들의 움직임은 현재 어른이 되어야할 우리들이 보여야하는 정적인 어른스러운 행동들과 대비된다. 작품을 통해 달콤했던 어릴적 상상들로 해방감을 맛보고 시원한 휴식이 되기를 바란다.",
        "art_explain_11" : "‘자개가 펼쳐지는 순간’은 한국 전통 자개를 하나의 세계를 품은 표면으로 바라보는 데서 출발한다. 자개 문양은 공예품 위에 고정된 무늬처럼 보이지만, 그 안에는 빛의 방향에 따라 달라지는 색, 겹겹이 쌓인 결에 따라 다르게 드러나는 이미지가 존재한다.\n\n이러한 자개의 특성을 바탕으로, 문양 안에 잠재되어 있던 세계가 현실의 공간으로 확장되는 순간을 상상한다. 자개는 빛과 움직임을 통해 생명력을 얻는 매개체가 되어 풍경과 생명, 기억을 품은 하나의 공간으로 보여준다.\n\n따라서 ‘자개가 펼쳐지는 순간’은 자개 문양 안에 숨겨진 세계를 현실로 불러내고 다시 문양으로 회귀시킨다. 고정된 문양은 잠시 움직이는 풍경이 되고, 표면은 하나의 공간으로 확장되며, 마지막에는 다시 자개의 결 안으로 돌아가 빛과 시간의 흔적으로 남는다.",
        "art_explain_12" : "어린 시절 우리는 생일 케이크의 촛불 앞에서 순수한 마음으로 소원을 빌었다. 그 소원은 때로는 사소하고 엉뚱했지만, 미래를 향한 솔직한 꿈과 희망이 담겨 있었다.\n\n하지만 시간이 흘러 어른이 된 우리는 현실의 무게 속에서 점차 물질적이고 현실적인 목표를 우선하게 된다. 그 과정에서 어린 시절 품었던 순수한 바람과 꿈들은 기억 속 깊은 곳에 묻혀버리기도 한다.\n\n본 작품은 잊고 지냈던 어린 시절의 소원을 다시 떠올리게 하며, 현재의 삶이 그때의 꿈과 얼마나 맞닿아 있는지 되묻는다. 촛불을 끄기 전 두 손을 모으던 순간의 설렘을 통해, 관람자가 자신의 내면에 남아 있는 소망과 가능성을 돌아보도록 유도한다.\n\n이 작품이 잊혀진 소원의 불씨를 다시 밝히고, 현재의 나를 다정하게 성찰하는 작은 계기가 되기를 바란다.",
        "art_explain_13" : "이 작품은 우리 전통 명절인 단오의 풍경을 바탕으로, 과거 사람들의 하루를 시간의 흐름에 따라 풀어낸 2D 미디어 아트이다.\n\n아침의 고요함에서 시작해 해가 저물고 밤이 찾아오기까지, 단오날의 다양한 순간들을 하나의 긴 풍경처럼 이어 담아내고자 했다.\n단오는 모내기를 마친 뒤 풍년과 안녕을 기원하며 잠시 삶을 쉬어가던 날이었다. 사람들은 창포물에 머리를 감고, 그네를 타고, 자연 속에서 서로 어울리며 계절의 변화와 삶의 안녕을 느꼈다. 작품 속 장면들은 이러한 단오의 풍습과 정서를 작은 움직임과 요소들로 풀어내며, 잊혀져가는 과거의 시간을 시각적으로 기록한다.\n\n특히 화면 전체가 천천히 흘러가는 구조를 통해, 단순한 풍경 재현이 아닌 ‘흘러가는 하루의 감각’을 전달하고자 했다.\n\n안개처럼 번지는 배경과 반복되는 움직임들은 기억 속 어딘가에 남아있는 옛 풍경의 잔상을 표현하며, 관람자로 하여금 잠시 과거의 시간 속을 거니는 듯한 경험을 마주하게 한다.",
        "art_explain_14" : "고전 서사인 오즈의 마법사와 한국 전래동화 심청전을 결합하여, 바다에 빠진 심청이가 낯선 세계에서 눈을 뜨는 순간을 영상으로 표현했다.\n\n작품 속 심청이는 드넓은 산과 다양한 물고기들을 마주하며 현실과 환상이 뒤섞인 공간을 지나간다. 화면은 뒤로 갈수록 색감이 변화하며 또 다른 세계의 모습을 드러내고, 동양적인 분위기와 판타지적인 이미지를 함께 담았다.\n\n이 작업은 추락이라는 상황을 단순히 부정적인 순간으로 바라보지 않는다. 아래로 떨어지는 과정 속에서도 새로운 풍경과 빛을 만나듯, 불안과 흔들림 또한 삶 속에서 지나가는 하나의 과정이자 아름다운 순간이 될 수 있음을 이야기하고자 했다.",
        "art_explain_15" : "우리가 마주한 스크린 속에는 빛과 색이 빚어낸 가장 순수하고 아름다운 바다가 흐르고 있다.\n몽환적인 파스텔톤으로 물든 물결은 자연이 가진 가장 부드러운 색채를 보여주고, 그 위로 부서지는 하얀 빛줄기는 찰나의 순간을 아름답게 밝힌다. 이 평화로운 공간을 가득 채우는 것은 역동적으로 살아 움직이는 물고기들이다. 저마다의 색을 품고 무리 지어 유영하는 움직임은 마치 자연이 추는 하나의 거대한 춤처럼 다가온다.\n\n복잡한 생각을 잠시 내려놓고, 자연이 만들어내는 감각적인 색채와 생동감 넘치는 생명의 에너지를 있는 그대로 느끼며 잔잔하게 일렁이는 물결을 따라 걷다 보면, 마음속 가득 기분 좋은 해방감이 채워질 것이다.",
        "art_explain_16" : "'천문'은 하늘에서 일어나는 일체의 자연 현상과 이를 연구하는 학문을 뜻한다.\n\n천문을 연구하듯 서울의 하늘을 새로운 시선으로 바라보며, 도심과 미디어가 하나의 풍경으로 어우러지는 밤하늘을 그린다. 검은 먹이 종이 위로 스며들듯 밤하늘 위에는 수묵이 퍼지고, 흩어진 별들은 점과 선이 되어 서로 연결된다.\n그렇게 서울의 밤하늘에 별자리처럼 이어진 한 폭의 수묵화가 펼쳐진다.",
        "art_explain_17" : "빠르게 돌아가는 서울 사회 속에서 사람들은 각자의 삶에만 집중한 채 살아간다. 같은 도시 안에 있지만 서로 연결되지 못하고 단절된 개인으로 존재한다. 그러나 서울은 다양한 사람들이 함께 살아가는 도시이며, 서로 다른 개성과 가치가 모일 때 더욱 큰 힘을 만들어낼 수 있다.\n\n해치와 해치프렌즈는 이러한 서울의 모습을 담아낸다. 단절되어 있던 존재들이 서로 연결되고 어우러지는 과정을 통해 서울의 다채로운 매력과 상생의 가치를 표현하며, 서로 다른 사람들이 함께할 때 더욱 든든한 공동체가 만들어진다는 메시지를 캐릭터로 밝고 친근하게 전달하고자 한다.",
        "art_explain_18" : "전통은 과거에 머무는 것이 아니라, 현재를 통과해 미래로 이어지는 통로이다.\n\n'경계'는 한국의 전통 요소의 아름다움과 가치를 현대적으로 재해석하여 서울의 리듬을 시각화한다.\n\n반복되는 패턴은 우리의 일상과 도시의 움직임을 담아내며, 복잡하고 어지러운 일상 속 잠시 멈춰 주변을 바라보게 한다.\n이를 통해 관람자는 전통이 지닌 고요한 색감과 절제된 아름다움을 경험하게 된다.\n\n이들은 경계가 아닌 통로로 작용하며, 전통과 현대, 내부와 외부를 넘나드는 경험을 만들어낸다.",
        "art_explain_19" : "우리는 매일 서울을 지나친다.\n빠르게 스쳐가는 창밖의 풍경 속에는 각기 다른 표정의 서울이 흐른다.\n\n본 작품은 지하철 창문 너머로 마주한 서울의 랜드마크와 도시의 풍경을 따라가며 하루를 담아낸다. 익숙하지만 쉽게 머무르지 못했던 서울의 아름다운 풍경을 잠시라도 천천히 바라보는 여유를 전하고자 한다.",
        "art_explain_20" : "‘바람’을 주제로 한 이 멀티미디어 아트 작품은 다양한 시선을 통해 서울의 다채로운 풍경을 표현한다. 화면은 바람의 움직임을 따라 자연스럽게 서울역, 남산타워, 경복궁 등 서울의 대표적인 명소들을 지나간다. 바람은 꽃잎으로 형상화되며, 꽃잎이 지나가는 곳마다 도시의 풍경은 동양 전통 회화의 분위기를 담은 장면으로 변화한다.\n\n작품의 색채와 구도는 한국 전통 회화인 「일월오봉도」에서 영감을 받아, 해와 달, 산과 강, 자연의 상징적 요소들을 현대적인 시각 언어로 재해석하였다. 관람자는 익숙한 서울의 풍경을 새로운 예술적 경관으로 경험하며, 도시와 자연, 전통과 현대가 조화롭게 어우러지는 시각적 향연을 느낄 수 있다.\n\n또한 서울을 처음 방문하는 관광객들에게는 이 작품이 하나의 도시 여행 지도로서 기능하며, 서울의 주요 관광 명소를 소개하는 역할도 수행한다.",
        "art_explain_21" : "침입은 주체가 뒤바뀌는 순간이다.\n\n인간은 자연을 점유하고, 그 위에 건물을 구축한다.\n그러나 자연은 사라진 것이 아니라, 다른 방식으로 그 공간에 잔존한다.\n\n이 프로젝트는 인간이 만든 구조 내부에서 드러나는 자연의 흔적을 통해, 공간의 주체가 누구인가에 대한 질문을 제기한다.\n\n침입은 단방향의 사건이 아니다.\n인간은 자연을 침범하고, 자연은 다시 인간의 공간으로.\n\n침입은 반복된다.",

        "art_explain_22" : "민화에 등장하는 소재들을 현대적으로 재해석하여 표현하고, 사계의 흐름으로 구성한 영상이다. 영상은 꽃과 새가 등장하는 화조도가 봄으로 표현되어 시작된다.\n\n이어서 비가 내리며 피어나는 수국과 그 주변을 맴도는 나비는 꽃과 벌레의 조합인 초충도를 상징하며, 봄과 여름 사이의 시기를 오묘한 분위기로 표현했다. 수국이 지며 자라나는 연잎과 연꽃, 어느 순간 날아드는 잠자리들은 수국과 나비의 조합과 마찬가지로 초충도를 상징하지만 한여름을 지나 다가오는 가을의 암시가 느껴지는,시간의 흐름을 달리 해석하게 한다.\n\n어느덧 무르익은 논밭과 벼,귀뚜라미,흩날리는 낙엽은 완연한 가을이 왔음을 알린다. 그리고 그 속에 두 마리의 학이 등장하고,학을 따라 비행하자 첩첩산중이 보여 진다. 학과 산은 장생도의 요소들이며,흩날리는 눈과 함께 겨울산의 풍경이 길고 긴 겨울처럼 끝없이 펼쳐지며 영상이 마무리된다.\n\n염원을 상징하는 민화의 요소들이 사계절로 구성된 것처럼 시간의 흐름마다 안정과 평화,소망이 이루어지기를 바라는 마음이다.",
        "art_explain_23" : "〈오랜만이야!〉는 가뭄으로 메말랐던 숲에 비가 내리며 생명들이 다시 살아나는 과정을 담은 그림 기반 영상 작품이다. 그림 같은 이미지와 붓터치의 느낌을 살려 숲의 변화를 자연스럽게 보여준다.\n\n갈라진 땅과 조용한 숲에서 시작해, 첫 빗방울이 떨어지면서 생명은 조금씩 움직이기 시작한다. 비는 숲을 되살리는 역할을 하며, 다양한 생명들이 서로 연결되어 있음을 보여준다. 이 작품은 자연이 다시 살아나는 모습과 함께 우리가 잊고 지냈던 자연의 감각을 다시 느끼게 한다.",
        "art_explain_24" : "3년 동안 거의 매일 아침, 같은 자리에서 산과 하늘을 바라보며 사진을 찍었다. 처음부터 어떤 목적이나 의도가 있었던 것은 아니다. 매일 지나치던 그 자리에서 바라본 풍경이 눈에 남았을 뿐이었다.\n\n같은 장소에서 같은 방향을 바라보았지만, 그곳은 항상 같은 모습이 아니었다. 날씨와 계절, 빛의 변화와 공기의 밀도에 따라 산과 하늘은 끊임없이 다른 모습을 드러냈다. 그 변화는 한 장의 사진만으로는 쉽게 보이지 않았지만, 시간이 쌓이면서 비로소 하나의 흐름을 만들어냈다.\n\n이 영상은 그렇게 모은 사진들을 페이드 방식으로 연결해 만든 것이다. 익숙한 풍경 속에 천천히 스며든 시간의 흐름, 그리고 그 안에서 일어난 변화를 시각적으로 담아내고자 했다.",
        "art_explain_25" : " 본 작품은 정형화된 인류의 회색 도시 문명 속에서 태동한 자연의 원초적 생명력을 통해, 미시적 세포와 거대한 대우주가 지닌 유기적 관계성과 영원한 순환을 탐색한다. 차가운 인공적 그리드를 깨뜨리고 솟아오른 다채로운 오브제들은 자연의 질서를 닮아가며 초현실적인 생태계로 순환하고, 이내 피고지며 만개해 나가는 꽃과 식물 줄기, 일렁이는 구체의 형태로 생명의 역동적인 에너지를 묘사한다.\n\n 이 미시적인 생명의 에너지는 점차 거대한 성운과 은하라는 거시적 우주 공간으로 확장하고 폭발하며, 자연의 모든 존재가 단절 없이 촘촘하게 연결되어 있음을 암시한다.\n\n앰비언트 사운드의 평안함과 함께 전개되는 이 시각적 퍼포먼스는 가장 작은 세포에서 시작해 무한한 대우주의 순환 속으로 환원되는 존재의 궤적을 따라가게 하고, 이를 통해 도심 속 관객들에게 화면을 넘어선 대자연의 색채적 아름다움과 시각적 심상의 유기적 관계에 대한  상상을 선사하고자 한다.",

        "time_table_title" : "전시 순서 안내",
        "time_table_title_1" : "예술",
        "time_table_title_2" : "동행",
        "time_table_title_3" : "매력",
        "time_table_title_sub_1" : "시작의 근원",
        "time_table_title_sub_2" : "모먼트 서울",
        "time_table_title_sub_3" : "한강 네이처",
        "time_table_art_1" : "1. 이돈아 〈무한한 행복을 향한 여정〉",
        "time_table_art_2" : "2. 최성록 〈서울하늘변신구름많음〉", 
        "time_table_art_3" : "",
        "time_table_art_4" : "3. 서울응원 봄메시지",
        "time_table_art_5" : "4. 해치와 서울나들이",
        "time_table_art_6" : "5. 꼬마 맹꽁이의 모험",
        "time_table_art_7" : "6. 이돈아 〈화조도〉",
        "time_table_art_8" : "7. 최성록 〈기원의 협곡〉",
        "time_table_art_9" : "",
        "time_table_art_10" : "8. 서울응원 봄메시지",
        "time_table_art_11" : "9. 해치와 서울나들이",
        "time_table_art_12" : "10. 꼬마 맹꽁이의 모험",

        "directions_title" : "오시는 길",

        "directions_explain_title_1" : "지하철",
        "directions_explain_title_2" : "버스",
        "directions_explain_title_3" : "자선 버스",

        "directions_explain_1" : "1호선\n용산역 5번출구 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004)\n노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차 -\n노들섬 동측 주차장 방면 진입로 통해 입장\n\n4호선\n신용산역 3번출구 - 도보 100m 위치 신용산역 정류장(03-004) -\n용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차 -\n노들섬 동측 주차장 방면 진입로 통해 입장\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동 - \n노들섬 동측 주차장 방면 진입로 통해 입장\n\n\n",
        "directions_explain_2" : "간선 버스\n150, 151, 152, 500, 504, 506,\n507, 605, 750A, 750B, 751, 752",
        "directions_explain_3" : "지선버스\n6211\n각 버스 하차 후 노들섬 동측 주차장 방면 진입로 통해 입장\n\n한강버스\n여의도 - 압구정 사이 구간에서 관람 가능",
    },
    en : {
        "index_button_introduce" : "About Seoullo Media Canvas",
        "index_button_schedule" : "Schedule",
        "index_button_exhibit" : "Exhibition Introduction",
        "index_button_exhibit_sub" : "",
        "index_button_art_1" : "The University Collaboration Exhibition",
        "index_button_art_1_sub" : "",
        "index_button_art_2" : "Nature Project Exhibition",
        "index_button_art_2_sub" : "",
        // "index_button_directions" : "Location",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        // "atelier_nodeul_name" : "아뜰리에 노들",
        // "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        // "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        // "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<Atelier Nodeul 2026 1st Exhibition : The Origin of All Beginnings> Timeline",
        "schedule_explain_date" : "Exhibition Period | March 22, 2026 (Fri) – July 31, 2026 (Fri)",
        "schedule_explain_pos" : "Venue | Media Façade under the southern pier of Hangang Bridge, \n             Nodeul Island",
        "schedule_explain_pos_detail" : "",
        "schedule_explain_time" : "Screening Hours | 20:00–22:00 (Screened every hour on the hour)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        // "exhibit_intro_title" : "Exhibition Introduction",        
        // "exhibit_introduce_name" : "Atelier Nodeul 2026 1ST EXHIBITION : The Origin of All Beginnings",
        "exhibit_introduce" : "Seoullo Media Canvas is a media art platform that expands the scope of media art by continuously displaying artworks made of electronic light, such as media art and video content that citizens can enjoy and sympathize with.",
        // "exhibit_introduce_sub" : "",
        // "exhibit_explain_name_1" : "The Origin of All Beginnings",
        // "exhibit_explain_1" : "'The Origin of All Beginnings' is a media art exhibition on Nodeul Island, where the lights of the city and the waters of the Hangang River come together.\n\nThrough the dynamic works of two media artists, the exhibition explores moments of origin and creation while highlighting the artistic charm of Nodeul Island and the new possibilities of the Hangang River.",
        // "exhibit_explain_name_2" : "Moment Seoul",
        // "exhibit_explain_2" : "'Moment Seoul' highlights one of Seoul's core values: a compassionate city that walks alongside the vulnerable.\nThrough Spring Message of Support from Seoul, it delivers messages of encouragement to citizens facing new beginnings, while Haechi’s Seoul Journey follows a journey from Nodeul Island to the skies above Seoul, set against the scenery of Nodeul Island and the Hangang River.",
        // "exhibit_explain_name_3" : "Hangang Nature",
        // "exhibit_explain_3" : "'Hangang Nature' represents Seoul's vision of 'Charm', presenting a media-art nature archive of the living ecology of Nodeul Island and the Hangang River.\n\nThrough an omnibus animation featuring the \"Maengkkongi\" the boreal digging frog, as its main character, the work follows a journey in search of a new home, conveying the island's ecology, seasonal changes, and the diverse landscapes of Seoul and the Hangang River.",
        
        "exhibit_2_intro_title" : "Exhibition Introduction",        
        "exhibit_2_introduce_name" : "2nd Exhibition 07.01.-09.19.",
        "exhibit_2_introduce" : "Seoullo Media Canvas' second exhibition in 2026 welcomes visitors with diverse views of the city, nature, and young creators amid the ripe summer scenery. The exhibition will consist of the Nature Project and the University Cooperation Exhibition, which will showcase the changing landscape of the city, the cycle of nature, and the new generation's sense of looking at it through media art.",
        // "exhibit_2_introduce_sub" : "",
        "exhibit_2_explain_name_1" : "The University Collaboration Exhibition",
        "exhibit_2_explain_1" : "The University Cooperation Exhibition introduces the fresh imagination and experimental gaze of university students who will lead the field of media art in the future. Works that interpret Seoul's daily and seasonal senses, tradition and modernity, and individual memories and emotions in various ways meet with citizens through public media platforms and create a new place of empathy.",
        "exhibit_2_explain_name_2" : "Nature Project Exhibition",
        "exhibit_2_explain_2" : "The Nature Project Exhibition explores the vitality, the passage of time, and the value of recovery and circulation that nature possesses. Works dealing with changes in the four seasons, restoration of ecosystems, records of nature in everyday life, and connectivity from microscopic life to the great universe offer various perspectives on nature and give viewers time to think.",
        // "exhibit_2_explain_name_3" : "Hangang Nature",
        // "exhibit_2_explain_3" : "'Hangang Nature' represents Seoul's vision of 'Charm', presenting a media-art nature archive of the living ecology of Nodeul Island and the Hangang River.\n\nThrough an omnibus animation featuring the \"Maengkkongi\" the boreal digging frog, as its main character, the work follows a journey in search of a new home, conveying the island's ecology, seasonal changes, and the diverse landscapes of Seoul and the Hangang River.",
        
        "link_button_text" : "Watch Video",

        "exhibit_name_1" : "The University Collaboration Exhibition",
        "exhibit_name_2" : "Nature Project Exhibition",

        "exhibit_list_1" : "Swimming",
        "exhibit_list_2" : "Where a Day is Baked",
        "exhibit_list_3" : "Latent Image",
        "exhibit_list_4" : "Petals of the Mind",
        "exhibit_list_5" : "A Square Summer in a Square Room",
        "exhibit_list_6" : "Summer Vacation",
        "exhibit_list_7" : "The Horse",
        "exhibit_list_8" : "Adapting in Our Own Ways",
        "exhibit_list_9" : "Beyond The Window",
        "exhibit_list_10" : "Sweet Summer",
        "exhibit_list_11" : "The Moment Nacre Unfolds",
        "exhibit_list_12" : "Make A Wish",
        "exhibit_list_13" : "A Day in June",
        "exhibit_list_14" : "A Fairy Tale",
        "exhibit_list_15" : "Shimmering Deep Wave",
        "exhibit_list_16" : "CheonMun",
        "exhibit_list_17" : "Seoul Soulmates",
        "exhibit_list_18" : "Threshold",
        "exhibit_list_19" : "Flowing Seoul",
        "exhibit_list_20" : "Wind Across Seoul",
        "exhibit_list_21" : "Intrusion",
        
        "exhibit_list_22" : "The Four Seasons",
        "exhibit_list_23" : "Hello Again, Rain",
        "exhibit_list_24" : "Today, That Mountain",
        "exhibit_list_25" : "Connection : From Cell to Galaxy",


        "exhibit_artist_name_1" : "Hwang Se Hee",
        "exhibit_artist_name_2" : "Jeon Soo Ah",
        "exhibit_artist_name_3" : "Park Ji Hyeon",
        "exhibit_artist_name_4" : "Kim Seo Yun",
        "exhibit_artist_name_5" : "Kwon Ye Ji",
        "exhibit_artist_name_6" : "Kim So Jeong",
        "exhibit_artist_name_7" : "Park Gyu Ri",
        "exhibit_artist_name_8" : "Lee Yeo Jin",
        "exhibit_artist_name_9" : "Yang I Saac",
        "exhibit_artist_name_10" : "Choi Su Bin",
        "exhibit_artist_name_11" : "Kang Ji su",
        "exhibit_artist_name_12" : "Lee Hye Jin",
        "exhibit_artist_name_13" : "Lee chae hyeon",
        "exhibit_artist_name_14" : "Won You Kyong",
        "exhibit_artist_name_15" : "Lee So hyung",
        "exhibit_artist_name_16" : "DANA KIM,\nCHAERIN LEE,\nYUGYEONG CHUNG",
        "exhibit_artist_name_17" : "NAHYUN KIM,\nDOHYANG KIM,\nSINYOUNG HWANG",
        "exhibit_artist_name_18" : "SUJIN KWON,\nJIYEON KIM,\nYERIM PARK",
        "exhibit_artist_name_19" : "CHANYOUNG SONG,\nJIHYE YU,\nSIEUN CHA",
        "exhibit_artist_name_20" : "JIALI CHEN,\nYUNJIA CHU,\nXIN LI ",
        "exhibit_artist_name_21" : "SONGLIM KIM,\nYUYEON NAM,\nSUAN EUN,\nNAYEON CHO",
        
        "exhibit_artist_name_22" : "Youngwoo Kim",
        "exhibit_artist_name_23" : "Nana",
        "exhibit_artist_name_24" : "CheolWon Chang",
        "exhibit_artist_name_25" : "injong Choi  ",


        "art_list_1" : "Swimming",
        "art_list_2" : "Where a Day is Baked",
        "art_list_3" : "Latent Image",
        "art_list_4" : "Petals of the Mind",
        "art_list_5" : "A Square Summer in a Square Room",
        "art_list_6" : "Summer Vacation",
        "art_list_7" : "The Horse",
        "art_list_8" : "Adapting in Our Own Ways",
        "art_list_9" : "Beyond The Window",
        "art_list_10" : "Sweet Summer",
        "art_list_11" : "The Moment Nacre Unfolds",
        "art_list_12" : "Make A Wish",
        "art_list_13" : "A Day in June",
        "art_list_14" : "A Fairy Tale",
        "art_list_15" : "Shimmering Deep Wave",
        "art_list_16" : "CheonMun",
        "art_list_17" : "Seoul Soulmates",
        "art_list_18" : "Threshold",
        "art_list_19" : "Flowing Seoul",
        "art_list_20" : "Wind Across Seoul",
        "art_list_21" : "Intrusion",
        
        "art_list_22" : "The Four Seasons",
        "art_list_23" : "Hello Again, Rain",
        "art_list_24" : "Today, That Mountain",
        "art_list_25" : "Connection : From Cell to Galaxy",


        "artist_name_1" : "Hwang Se Hee",
        "artist_name_2" : "Jeon Soo Ah",
        "artist_name_3" : "Park Ji Hyeon",
        "artist_name_4" : "Kim Seo Yun",
        "artist_name_5" : "Kwon Ye Ji",
        "artist_name_6" : "Kim So Jeong",
        "artist_name_7" : "Park Gyu Ri",
        "artist_name_8" : "Lee Yeo Jin",
        "artist_name_9" : "Yang I Saac",
        "artist_name_10" : "Choi Su Bin",
        "artist_name_11" : "Kang Ji su",
        "artist_name_12" : "Lee Hye Jin",
        "artist_name_13" : "Lee chae hyeon",
        "artist_name_14" : "Won You Kyong",
        "artist_name_15" : "Lee So hyung",
        "artist_name_16" : "DANA KIM, CHAERIN LEE, YUGYEONG CHUNG",
        "artist_name_17" : "NAHYUN KIM, DOHYANG KIM, SINYOUNG HWANG",
        "artist_name_18" : "SUJIN KWON, JIYEON KIM, YERIM PARK",
        "artist_name_19" : " CHANYOUNG SONG, JIHYE YU, SIEUN CHA",
        "artist_name_20" : "JIALI CHEN, YUNJIA CHU, XIN LI ",
        "artist_name_21" : "SONGLIM KIM, YUYEON NAM, SUAN EUN, NAYEON CHO",
        
        "artist_name_22" : "Youngwoo Kim",
        "artist_name_23" : "Nana",
        "artist_name_24" : "CheolWon Chang",
        "artist_name_25" : "injong Choi  ",


        "art_explain_1" : "\"Swimming(Yuyoung)\" is a work that vividly captures the movement of slowly passing clouds and flowers swaying in the breeze, viewed while gazing up at the sky from a field of cosmos flowers.\n\nEarly June is the season when life breathes most vibrantly.\nLying in a field of cosmos spread out beneath the blue sky, one fully experiences the air and the flow of the moment—as if drifting through summer itself.\n\nIt invites modern people, caught in the rapid pace of urban life, to pause for a moment and slowly immerse themselves in the sky and the sensations of the season—things often overlooked in the rush of daily routine.\n\nSwimming through the gentle flow of a June moment.",
        "art_explain_2" : "In the fast-paced daily life of Seoul, people are prone to constantly moving and losing their composure.\nThe artist also felt that there was not enough time to rest for a while in a busy life, so he tried to express a warm space of rest based on this experience.\n\nSo, I set the concept of 'Apple pie shop of rats' where time flows at a different speed from reality.\nThe small rats slowly baked the apple pie and enjoyed a picnic, capturing a slow and cozy time, and adding a small vitality to the calm daily life with a scene in which they were busy moving in surprise of the rolling apples.\n\nI hope this work will stop for a while in a busy daily life and become a small comma to remind you of relaxation and healing.",
        "art_explain_3" : "'LATENT IMAGE' is a photographic term that means an image recorded on film but not yet visible.\nThis work is a pattern-based media work that expresses these concepts by connecting them to images of dreams and memories.\n\nThe shape and pattern of flowers in the video are repeated, expanded, and constantly changed. The blurred shape is briefly clearly revealed and then disappeared again, and different images overlap to create a new scene.\nRepeatedly changing patterns symbolize the fragments of memories and the flow of emotions that rise in dreams.\n\nIn our dreams, we often experience real-life memories, emotions, and familiar scenes appearing in unexpected ways. The work visualizes these dream characteristics through patterns and movements, and captures the moment when an invisible image rises and disappears.\n\nViewers follow the afterimage of dreams and memories in the ever-changing shape and flow, and face their own emotions and imaginations.",
        "art_explain_4" : "It is a media art work that expresses the invisible flow of emotions in the form of organic flowers and soft movements.\n\nWe live by experiencing various emotions such as joy, anxiety, excitement, and tranquility in our daily lives. However, emotions are not defined as a form, but are mixed with each other and constantly changing.\nThis work visualizes this flow of emotion as an abstract flower shape and natural movement.\n\nThe form of a flower symbolizes the process of blooming and dispersing repeatedly, and emotion is created and changed.\nThe organic movements that overlap each other show emotions changing and circulating over time.\n\nIn addition, it tried to express the movement of invisible emotions through the smooth flow of shape and texture.\nThe constantly changing shape of a flower shows the process of complex emotions blooming and disappearing in a single flow, and visually unravels the formless inner emotions.",
        "art_explain_5" : "The beach that reminds me of summer. Even if I can't go to my room in person due to busy days You can enjoy the sea in an aquarium toy.\nTime flies when you stare blankly at the sea unfolding in a small, square area.\n\nIt's like looking at a square aquarium in a square room, on a square screen of Seoullo media.",
        "art_explain_6" : "Summer vacation is a video about a journey to find a sense of complete liberation in the bustling daily life of the city center.\n\nWhen the screen is changed after passing through the night view of the desolate city full of neon signs, the emerald blue sea unfolds in front of your eyes with a glass of cool cocktails.\n\nThey move to an exotic and peaceful space that everyone dreams of at least once, escaping from overtime work and difficult daily life. The scenery of the resort, which unfolds through the day and night, relieves the frustration of being trapped, moves into a space that seems to be dreaming, and gives a sense of freedom to escape the tired daily life.",
        "art_explain_7" : "Marking the year of the horse in 2026, the year of the disease and the year of the horse, a video of horses of various looks crossing the screen in their own steps was produced.\nThe words in the video symbolize the appearance of us living constantly moving in our own directions even in our repeated daily lives. Some horses run fast, and some walk slowly. The size, shape, and speed are all different, but all horses move forward in their own rhythms.\n\nWe often live by comparing ourselves based on the speed and direction of others. However, this work attempted to explain that life itself is meaningful in its own way, through the appearance of beings with different appearances and speeds moving together within the same screen.\n\nThe words in the video continue to move without a set destination. This resembles how we have to constantly move forward in a busy modern society\nThere is. Not everyone is on the same path, but it's the same in that they are silently moving in their own direction in their respective positions.\n\nThis work was created to re-examine the direction and movement of each person's life through scenes in which beings with different speeds and shapes flow together in one space.",
        "art_explain_8" : "Jelly bears living in cities are all born in the same shape, but they live completely different lives depending on the environment they face.\nIt melts under hot light, moves to avoid danger, and sometimes adapts to the new environment as it has changed.\nThis work looks at the space of the city as a reduced society and expresses the various ways of survival of beings that vary depending on the environment even if they start under the same conditions.",
        "art_explain_9" : "In the small room where the night fell, a small paper plane flies in front of the boy who was immersed in boredom. The boy follows the paper plane without hesitation, and eventually shows impulsive behavior enough to throw himself out the window.\n\nAt that moment, the person next to him hurriedly grabs the boy and faces a short moment of crisis together.\n\nThis work is a 3D anamorphic media facade video produced based on the world view of 'PROJECT: SHOMA', and it is intended to capture the relationship between the two characters, the personality difference revealed by their actions, and the flow of emotions in a short narrative.\n\nThe video is based on an emotional structure that starts with boredom and leads to curiosity, immersion, tension, relief, and lingering feelings, and emphasizes the continuity and immersion of the space through a fixed camera and one-take format. In addition, part of the world view of the work was implicitly expressed through various visual elements such as frames and urban landscapes in the background.",
        "art_explain_10" : "With 'summer' and 'childhood innocence' as keywords, the space in the city center is reminded with refreshing imaginations.\n\nIt depicts the fantasy that everyone dreamed of at least once as a child, such as a huge slide that separates the air against gravity, touching the floating clouds and tasting them like cotton candy, swimming in the sky on numerous balloons, and tasting the walls of ice cream.\n\nThe blue sky of summer and the movements of gummy bears swimming in it contrast to the static adult behaviors that we, who are now adults, must show. I hope you will enjoy a sense of liberation with sweet childhood imaginations through your work and have a cool rest.",
        "art_explain_11" : "\"The Moment Nacre Unfolds\" starts with a view of traditional Korean mother-of-pearl as a surface that embraces one world. The mother-of-pearl pattern looks like a fixed pattern on a craft, but there are colors that vary depending on the direction of light and images that are revealed differently depending on the layered texture.\n\n Based on these characteristics of mother-of-pearl, we imagine the moment when the world latent in the pattern expands into a real space. Mother-of-pearl becomes a medium that gains vitality through light and movement and shows it as a space that embraces scenery, life, and memory.\n\nTherefore, the 'moment when mother-of-pearl unfolds' invokes the world hidden in the mother-of-pearl pattern into reality and returns it to the pattern. The fixed pattern briefly becomes a moving landscape, the surface expands into a single space, and at the end, it returns to the decision of mother-of-pearl and remains as a trace of light and time.",
        "art_explain_12" : "As a child, we made a wish with pure heart in front of the candle on the birthday cake. The wish was sometimes trivial and quirky, but it contained honest dreams and hopes for the future.\n\nBut as time passes, as adults, we gradually prioritize material and realistic goals under the weight of reality. In the process, pure wishes and dreams from childhood are buried deep in memory.\n\nThis work reminds me of my childhood wish that I had forgotten, and asks again how much my present life is in contact with my dreams at that time. Through the excitement of the moment when my hands were together before the candle was extinguished, it encourages viewers to look back on the wishes and possibilities that remain within them.\n\nI hope this work will be a small opportunity to re-light the embers of forgotten wishes and reflect fondly on myself in the present.",
        "art_explain_13" : "Based on the landscape of Dano, our traditional holiday, this work is a 2D media art that unravels people's days in the past with the passage of time.\n\nFrom the calm of the morning to the sunset and the night came, I tried to capture the various moments of Dano like a long landscape.\nAfter planting rice, Dano was a day to take a break from life, wishing for a good harvest and well-being. People washed their hair in Changpomul, rode a swing, mingled with each other in nature, and felt the change of season and the well-being of life. The scenes in the work visually record the time of the forgotten past, unraveling these Dano customs and emotions into small movements and elements.\n\nIn particular, through a structure in which the entire screen flows slowly, it was intended to convey the \"sense of a flowing day\" rather than a simple representation of the landscape.\n\nThe fog-like background and repeated movements express the afterimage of the old landscape that remains somewhere in the memory, and allow the viewer to face the experience of walking in the time of the past for a while.",
        "art_explain_14" : "Combining the classic narrative of The Wizard of Oz and the Korean traditional fairy tale Shimcheongjeon, Shimcheong-i, who fell into the sea, opened her eyes in an unfamiliar world.\n\nShim Cheong-i in the work passes through a space where reality and fantasy are mixed while facing a wide mountain and various fish. The color of the screen changes as it goes back, revealing another world, and capturing oriental atmosphere and fantasy images together.\n\nThis work does not simply look at the situation of falling as a negative moment. Just as we encounter a new landscape and light in the process of falling down, I wanted to talk about how anxiety and shaking can also be a process and a beautiful moment in life.",
        "art_explain_15" : "In the screen we face, the purest and most beautiful sea of light and color flows.\nThe waves colored in dreamy pastel tones show the softest colors of nature, and the white beams of light that break above them beautifully illuminate the moment. It is the dynamic fish that live and move that fill this peaceful space. The movement of swimming in groups with each color comes as if it were a huge dance of nature.\n\nIf you put down your complex thoughts for a while and walk along the calm waves while feeling the sensuous colors and lively energy of life created by nature as it is, you will be filled with a pleasant feeling of liberation.",
        "art_explain_16" : "\"CHEONMUN\" refers to all natural phenomena occurring in the sky and the study of them.\n\nLooking at the sky of Seoul with a new perspective as if studying astronomy, it paints a night sky in which the city center and the media are harmonized into a single landscape. Ink spreads over the night sky like black ink permeates over paper, and the scattered stars become dots and lines and connect each other.\nIn this way, an ink-and-wash painting that connects like a constellation unfolds in the night sky of Seoul.",
        "art_explain_17" : "In a fast-paced Seoul society, people live their lives focusing only on their own lives. They exist as individuals who are in the same city but are not connected to each other and are disconnected. However, Seoul is a city where diverse people live together, and when different personalities and values come together, they can create greater power.\n\nHatch and Hatch Friends capture this image of Seoul. Through the process of connecting and harmonizing the disconnected beings with each other, we want to express Seoul's colorful charm and the value of co-prosperity, and convey the message that a stronger community is created when different people are together as characters.",
        "art_explain_18" : "Tradition does not stay in the past, but is a passage through the present and into the future.\n\n'Boundary' visualizes the rhythm of Seoul by modernly reinterpreting the beauty and value of traditional elements of Korea.\n\nRepeated patterns capture our daily lives and city movements, allowing us to pause for a moment to look around in a complicated and dizzy daily life.\nThrough this, viewers experience the tranquil colors and restrained beauty of tradition.\n\nThey act as channels, not boundaries, and create experiences that cross tradition and modernity, inside and outside.",
        "art_explain_19" : "We pass by Seoul every day.\nSeoul with different expressions flows in the scenery outside the window that passes quickly.\n\nThis work captures the day while following the landmarks of Seoul and the cityscapes that face over the subway window. I would like to convey the relaxation of slowly looking at the beautiful scenery of Seoul, which was familiar but could not be easily stayed.",
        "art_explain_20" : "Under the theme of \"Wind,\" the multimedia artwork expresses Seoul's colorful landscape through various perspectives. The screen naturally follows the movement of the wind and passes through Seoul's representative attractions such as Seoul Station, Namsan Tower, and Gyeongbokgung Palace. The wind is embodied in petals, and wherever the petals pass, the cityscape changes into a scene containing the atmosphere of traditional oriental painting.\n\nThe color and composition of the work were inspired by the traditional Korean painting \"Ilwol Obongdo\", and the symbolic elements of the sun and moon, mountains and rivers, and nature were reinterpreted in modern visual language. Visitors can experience the familiar scenery of Seoul as a new artistic landscape and feel a visual feast in which the city and nature, tradition and modernity are harmoniously harmonized.\n\nFor tourists visiting Seoul for the first time, the work functions as a city tour map and also serves to introduce Seoul's major tourist attractions.",
        "art_explain_21" : "An invasion is the moment when the subject is reversed.\n\nHumans occupy nature and build buildings on it.\nHowever, nature has not disappeared, but remains in the space in a different way.\n\nThis project raises the question of who the subject of space is through the traces of nature revealed inside human-made structures.\n\nThe invasion is not a one-way event.\nMan invades nature, and nature enters human space again.\n\nThe invasion is repeated.",
        
        "art_explain_22" : "It is a video composed of the flow of the four seasons, reinterpreting and expressing the materials in folk paintings in a modern way. The video begins with the expression of a flower and bird in spring.\n\nSubsequently, the hydrangeas blooming in the rain and the butterflies hovering around them symbolize Chochungdo, a combination of flowers and bugs, and express the period between spring and summer with a subtle atmosphere. Lotus leaves and lotus growing as the hydrangeas build, and dragonflies flying at some point, symbolize Chochungdo, just like the combination of hydrangeas and butterflies, but allow us to interpret the passage of time differently, with hints of autumn coming after midsummer.\n\nThe ripe rice fields, rice, crickets, and falling leaves indicate that autumn has come. Two cranes appear in it, and as they fly along the crane, they can see the mountainside. The crane mountain is an element of Jangsaengdo, and the video ends with the scenery of the winter mountain spreading endlessly like a long winter with the drifting snow.\n\nJust as the elements of folk painting that symbolize desire consist of four seasons, I hope that stability, peace, and hope will be achieved in each passage of time.",
        "art_explain_23" : "\"Hello Again, Rain\" is a picture-based video work about the process of reviving life by raining on a dry forest. It shows the changes of the forest naturally by utilizing the picturesque image and the feeling of brush touch.\n\nLife begins to move little by little as the first raindrops fall, starting from the cracked land and quiet forest. Rain plays a role in reviving the forest and shows that various lives are connected to each other. This work makes us feel the sense of nature that we have forgotten as well as the way nature comes to life again.",
        "art_explain_24" : "For three years, I took pictures almost every morning, looking at the mountains and the sky in the same place. There was no purpose or intention from the beginning. The view from the spot that I passed by every day was just noticeable.\n\nWe looked in the same direction in the same place, but it didn't always look the same there. The mountains and the sky constantly changed depending on the weather, season, change in light, and density of air. The change was not easy to see with just a single photograph, but it was only as time increased that a flow was created.\n\nThis video is made by linking the photos collected in such a way in a fade method. It was intended to visually capture the passage of time that slowly permeated the familiar landscape and the changes that occurred in it.",
        "art_explain_25" : "This work explores the organic relationship and eternal cycle of microscopic cells and giant Daewooju through the primal vitality of nature born in the grey urban civilization of standardized humanity. The colorful objects that have broken the cold artificial grid resemble the order of nature, circulate into a surreal ecosystem, and depict the dynamic energy of life in the form of flowers, plant stems, and circulating spheres that soon bloom and bloom.\n\n This microscopic energy of life gradually expands and explodes into the macroscopic cosmic space of giant nebulae and galaxies, suggesting that all beings in nature are tightly connected without disconnection.\n\nThis visual performance, which develops with the peace of ambient sound, follows the trajectory of existence starting with the smallest cells and returning to the infinite cycle of Daewooism, thereby giving the audience in the city an imagination of the organic relationship between the color beauty of nature and visual imagery beyond the screen.",

        // "time_table_title" : "Information",
        // "time_table_title_1" : "Art",
        // "time_table_title_2" : "DongHaeng\n(empathy)",
        // "time_table_title_3" : "MaeRyeok\n(charming)",
        // "time_table_title_sub_1" : "The Origin of All Beginnings",
        // "time_table_title_sub_2" : "Moment Seoul",
        // "time_table_title_sub_3" : "Hangang Nature",
        // "time_table_art_1" : "1. Lee Donah 〈Odyssey to Infinite Happiness〉",
        // "time_table_art_2" : "2. Choi Sungrok 〈Seoul Sky of Transforming Clouds〉",
        // "time_table_art_3" : "",
        // "time_table_art_4" : "3. Spring Message of Support from Seoul",
        // "time_table_art_5" : "4. Haechi's Seoul Journey",
        // "time_table_art_6" : "5. Little Maengkkongi's Adventure",
        // "time_table_art_7" : "6. Lee Donah 〈Hwajodo in Space〉",
        // "time_table_art_8" : "7. Choi Sungrok 〈Genesis Canyon〉",
        // "time_table_art_9" : "",
        // "time_table_art_10" : "8. Spring Message of Support from Seoul",
        // "time_table_art_11" : "9. Haechi's Seoul Journey",
        // "time_table_art_12" : "10. Little Maengkkongi's Adventure",

        // "directions_title" : "Location",

        // "directions_explain_title_1" : "Subway",
        // "directions_explain_title_2" : "Bus",
        // "directions_explain_title_3" : "Green Bus (Local Route)",

        // "directions_explain_1" : "Line 1\nYongsan Station - Exit 5 → Walk about 300m to Yongsan Station\nBus Stop (03-004) → Take a bus toward Nodeul Island → Get off at\nNodeul Island Stop (03-340) → Enter via the access road next to the East Parking Gate\n\nLine 4\nSinyongsan Station – Exit 3 → Walk 100m to Sinyongsan Station\nBus Stop (03-004) → Take a bus toward Yongsan / Nodeul Island →\nContinue toward Hangang Bridge for about 700m → Get off at Nodeul Island Stop (03-340) → Enter via the access road next to the East Parking Gate\n\nLine 9\nNodeul Station - Exit 2 → Walk approximately 700m toward\nHangang Bridge → Enter via the access road next to the East Parking Gate\n",
        // "directions_explain_2" : "Blue Bus (Main Routes)\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752",
        // "directions_explain_3" : "6211\n→ Get off and enter via the access road next to the East Parking Gate\n\nHangang Bus\nThe exhibition is visible while riding between Yeouido and Apgujeong.",
    },
    ja : {
        "index_button_introduce" : "(일본어)아뜰리에 노들 소개",
        "index_button_schedule" : "(일본어)상영 시간표",
        "index_button_exhibit" : "(일본어)예술 미디어스케이프",
        "index_button_exhibit_sub" : " ",
        "index_button_art_1" : "(일본어)동행 모먼트서울",
        "index_button_art_1_sub" : " ",
        "index_button_art_2" : "(일본어)매력 한강네이처",
        "index_button_art_2_sub" : " ",
        
        "back_button_text" : "BACK",
        "top_button_text" : "(일본어)Top",
        "list_button_text" : "list",
        "prev_button_text" : "(일본어)이전",
        "next_button_text" : "(일본어)다음",

        "schedule_explain_name" : "(일)아뜰리에노들 미디어아트 상영 시간표",
        "atelier_nodeul_name" : "(일본어)아뜰리에 노들",
        "atelier_nodeul_explain" : "(일본어)아뜰리에 노들 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "schedule_name" : "(일)작품명",
        "schedule_time" : "(일)상영 시간",

        "exhibit_title" : "(일본어)전시 소개",        
        "exhibit_introduce" : "(일본어)전시 소개\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        "exhibit_explain" : "(일본어)전시 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "link_button_text" : "(일본어)영상 보러가기",

        "exhibit_name_1" : "(일)예술: 미디어스케이프 (Mediascape)",
        "artist_name_1" : "(일본어)작가명1",
        "art_name_1" : "(일본어)작품명1",
        "art_explain_1" : "(일본어)작품 설명1\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_2" : "(일본어)전시명2",
        "artist_name_2" : "(일본어)작가명2",
        "art_name_2" : "(일본어)작품명2",
        "art_explain_2" : "(일본어)작품 설명2\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_3" : "(일본어)전시명3",
        "artist_name_3" : "(일본어)작가명3",
        "art_name_3" : "(일본어)작품명3",
        "art_explain_3" : "(일본어)작품 설명3\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",

        "directions_explain" : "(일)지하철\n1호선\n용산역 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004) 노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번 출구 - 도보 100m 위치 신용산역 정류장(03-004) 용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n\n버스\n간선 버스\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\n자선 버스\n6211"
    }
    
}
